### ISSUE TITLE
[BUG] Composer is not found

### ISSUE THREAD

**Issue by fhferreira** [TiagoSilvaPereira/vemto-issues#1]
I've created one simple "project" and I receive that error about "composer" on "Generate" button. 

[MacOS BigSur]
Error: Command failed: composer /bin/sh: composer: command not found

![image](https://user-images.githubusercontent.com/140686/93963362-5cc81f80-fd33-11ea-94d0-3d7bfe0d6019.png)

**Comment by fhferreira** [comment]
Just to add more info:
![image](https://user-images.githubusercontent.com/140686/93964488-158f5e00-fd36-11ea-9119-ffc210a4f971.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @fhferreira please check if Composer is accessible calling it from the folder you created the project on your terminal

**Comment by TiagoSilvaPereira** [comment]
Hi @fhferreira I just added a way to configure the composer path on Vemto
![image](https://user-images.githubusercontent.com/11933789/94169331-0f4bcf80-fe65-11ea-9f75-7ba6e98f474a.png)

**Comment by fhferreira** [comment]
To update I should download the "DMG" again or you will provide an feature to automatically update?

**Comment by fhferreira** [comment]
@TiagoSilvaPereira I've downloaded the last version of Vemto but the problem persist.

![image](https://user-images.githubusercontent.com/140686/94188381-ade52a00-fe7f-11ea-98d5-481dca219028.png)

**Comment by fhferreira** [comment]
the path is already the composer bin, not a directory. 
![image](https://user-images.githubusercontent.com/140686/94188473-d2d99d00-fe7f-11ea-8a10-c10edb0e7b3a.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @fhferreira please remove the composer from the path and keep only /usr/local/bin/

Vemto updates automatically after you open it (please wait to the message after the download), then close and open it again

**Comment by asharekh** [comment]
hi, 

i have done everything, still not working

this is the error:
`Starting code generation!
Checking php
Checking composer
Command failed: /usr/local/bin/composer --version /bin/sh: /usr/local/bin/composer: is a directory
Command failed: /usr/local/bin/composer --version /bin/sh: /usr/local/bin/composer: is a directory
Sorry, Vemto requires composer installed in your system. Please check if composer is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page
Error: Sorry, Vemto requires composer installed in your system. Please check if composer is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page at p.checkDependency (app://./js/chunk-common.9e74499f.js:1:29099) at Xt.checkDependencies (app://./js/generator.f8b0147f.js:1:63134) at Xt.start (app://./js/generator.f8b0147f.js:1:62232) at EventEmitter. (app://./js/generator.f8b0147f.js:1:65369) at EventEmitter.emit (events.js:210:5) at Object.onMessage (electron/js2c/renderer_init.js:2243:16)`

**Comment by TiagoSilvaPereira** [comment]
Hi @asharekh as you can see on your error message:

```
/bin/sh: /usr/local/bin/composer: is a directory
```

It means that your composer binary is not inside the /usr/local/bin directory. Maybe it is on /usr/local/bin/composer?

You need to set the exact folder that contains de composer binary.

**Comment by brianmcaudill** [comment]
I am having an issue on Windows 10, the application is using composer with a single dash command and it should be a double dash. 
Example:
composer --version (is correct)
composer -version (incorrect)

**Comment by TiagoSilvaPereira** [comment]
@brianmcaudill could you please show the problem happening on Vemto console?

**Comment by brianmcaudill** [comment]
![image](https://user-images.githubusercontent.com/329199/169298367-e5435b25-411a-4255-9659-d28a609bde4b.png)

**Comment by brianmcaudill** [comment]
Here is the npm log for that error
[2022-05-19T13_01_18_114Z-debug.log](https://github.com/TiagoSilvaPereira/vemto-issues/files/8729279/2022-05-19T13_01_18_114Z-debug.log)

**Comment by TiagoSilvaPereira** [comment]
I think the ```-version``` is only a visual problem (for some reason it is hiding the first "-" when showing it, but Vemto correctly adds the ```--version``` when executing the command)... to fix the npm problem, if you can, please try deleting all the generated code and generating it again. If you can't do it, plase run npm install manually from your command line

**Comment by brianmcaudill** [comment]
I started with only these files in the folder
.env.example
composer.json
package.json

I ran the Generator and received these messages:
![image](https://user-images.githubusercontent.com/329199/169309047-ac6545c4-968f-4d8c-a150-b787999840e0.png)

![image](https://user-images.githubusercontent.com/329199/169309163-5879d8f4-f5b4-4490-a455-dc5630c9b0a6.png)

**Comment by cnngraphics** [comment]
I almost purchased this license, but after 10 hours of trying to configure the software's composer connection, I give up and would not recommend it to my team.

![image](https://user-images.githubusercontent.com/1514378/171970172-5bf4fa6f-1e3d-4bae-b514-47b8aa737e2f.png)

I have other software installed on my system like the very famous "LARAGON" it detects composer path and if not allows me to know during configuration if the path is wrong. 

When multiple users are having the same problem with your tool, the author should wonder if they need to do something differently.

**Comment by TiagoSilvaPereira** [comment]
> I almost purchased this license, but after 10 hours of trying to configure the software's composer connection, I give up and would not recommend it to my team.
> 
> ![image](https://user-images.githubusercontent.com/1514378/171970172-5bf4fa6f-1e3d-4bae-b514-47b8aa737e2f.png)
> 
> I have other software installed on my system like the very famous "LARAGON" it detects composer path and if not allows me to know during configuration if the path is wrong.
> 
> When multiple users are having the same problem with your tool, the author should wonder if they need to do something differently.

Hi @cnngraphics, most composer issues happen when Vemto can't locate it on your system (generally just passing the composer path and restarting Vemto is sufficient)... Could you please share how did you try to configure it? 

Also, you can always call me by e-mail to help if necessary (contact@vemto.app)
