### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StanMenten99** [TiagoSilvaPereira/vemto-issues#102]
**Describe the bug**
When adding the location for composer and PHP its not found
![image](https://user-images.githubusercontent.com/26350392/113509809-d13c1080-9557-11eb-9783-3c0cb7b3572a.png)

**Expected behavior**
I want it to connect to my WSL2 environment with Docker from a Windows 10 machine.

**Desktop (please complete the following information):**
 Windows 10 Home with Docker and WSL2

**Comment by TiagoSilvaPereira** [comment]
Hi @StanMenten99 I'm not sure that Vemto can execute a binary through WSL... I recommend installing composer and php on Windows to use them with Vemto

**Comment by StanMenten99** [comment]
That would defeat the whole purpose for using WSL on my Windows PC.
I use Docker with WSL2 because I **don't** want to install any dependencies on my PC, except for my IDEA, database manager and other tools.

Please make it work, then I will consider buying Vemto.

**Comment by TiagoSilvaPereira** [comment]
I'll check if there is a way to do it. Thanks!

**Comment by StanMenten99** [comment]
> I'll check if there is a way to do it. Thanks!

Any updates on this perhaps?

**Comment by TiagoSilvaPereira** [comment]
@StanMenten99 It is not possible for Vemto 1.x due to its architecture... I'm creating Vemto 2.x with a better architecture that will support running through WSL
