### ISSUE TITLE
[BUG] does not generate

### ISSUE THREAD

**Issue by ddiaz2380** [TiagoSilvaPereira/vemto-issues#103]
**To Reproduce**
It does not generate any new project or those that already had the new version.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57850481/113669243-d9946880-9689-11eb-94b7-d58727ace07f.png)
![image](https://user-images.githubusercontent.com/57850481/113669261-def1b300-9689-11eb-92cc-99a190114e56.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [0.8.1]

**Additional context**
It does not generate any new project or those that already had the new version.

**Comment by TiagoSilvaPereira** [comment]
Hi @ddiaz2380 seems like the **git clone** command is not selected for the **Code Generation**. Please be sure to select this command if you want to generate a complete project:

![image](https://user-images.githubusercontent.com/11933789/113723951-3d3d8680-96c8-11eb-8517-d91e505e6ebb.png)
