### ISSUE TITLE
[SUGGESTION] need a search bar for the list of apps

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#104]
[SUGGESTION] need a search bar for the list of apps

if there are a large number of applications, it becomes difficult to quickly find the right one

![nnn_7 ](https://user-images.githubusercontent.com/80303996/113755885-02286b00-973b-11eb-93df-3e7f40cff64b.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 thank you for your suggestion... I just added it to version **0.8.2**. Cheers
