### ISSUE TITLE
App from configuration file

### ISSUE THREAD

**Issue by jvallef** [TiagoSilvaPereira/vemto-issues#105]
You're doing a great job.

At some time allow generate whole application from command line and/or from Vemto app, from yaml files or any configuration file.

Work in visual mode it's slow for some kind of applications.

Thanks
Jose

**Comment by TiagoSilvaPereira** [comment]
Hi @jvallef thank you for your suggestion... The initial idea of Vemto is to run with a GUI, so it would be hard to change it to work on the command line, but I'll add this idea to my future suggestions list. Thanks!!
