### ISSUE TITLE
[BUG] Vento doesn't detect npm if node was installed using NVM

### ISSUE THREAD

**Issue by frankirox** [TiagoSilvaPereira/vemto-issues#107]
**Describe the bug**
Vento doesn't detect npm if node was installed using NVM

**To Reproduce**
1. Install NVM https://github.com/nvm-sh/nvm
2. Install node using nvm: nvm install 12.22.0 && nvm alias default 12.22.0
3. Try to export laravel application having npm using NVM

**Expected behavior**
Laravel application successfully exported

**Screenshots**
![image](https://user-images.githubusercontent.com/1335554/113919587-ad88fc80-97db-11eb-9a82-3092b902ce85.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - AppImage 0.8.2

**Comment by frankirox** [comment]
solved adding this to my .bashrc file: e xport PATH=`which node`:`which npm`:`which npm`:$PATH

**Comment by frankirox** [comment]
After adding this to my bashrc file the problem is still there but having a different message: export PATH=`which node`:`which npm`:`which npm`:$PATH

![image](https://user-images.githubusercontent.com/1335554/113921405-df9b5e00-97dd-11eb-9af2-1d89fc7aa89d.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @frankirox could you please share how are the environment settings on the Vemto homepage?

You can see how to access these settings here: https://vemto.app/docs/0.x/configuration

**Comment by TiagoSilvaPereira** [comment]
Hi @frankirox could you please share the Environment Settings?

**Comment by TiagoSilvaPereira** [comment]
Hey @frankirox I'm closing for now, as it seems there is no bug (it is probably the way the npm path was set on Vemto settings). But please feel free to comment here or call me if you have any questions or if I could help you. Cheers
