### ISSUE TITLE
[BUG] after updating to 0.8.2 - errors during testing (which were not there on 0.8.1)

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#108]
!!!!  ALL MODELS CONTAINING JSON COLUMNS AND WORKING ON 0.8.1 NOW ON 0.8.2 GIVE THE FOLLOWING ERROR WHEN TESTED
(while the forms that update the data in the columns continue to work)

The result of running php artisan test:

  • Tests\Feature\Controllers\VidyObjectovControllerTest > it updates the vidy objectov  ErrorException

  Undefined index: add_keys_fields

  at C:\laragon\www\pozadmin\app\Http\Controllers\VidyObjectovController.php:194
    190▕                 ->store('public');
    191▕         }
    192▕
    193▕         $validated['add_keys_fields'] = json_decode(
  ➜ 194▕             $validated['add_keys_fields'],
    195▕             true
    196▕         );
    197▕
    198▕         $vidyObjectov->update($validated);

  1   C:\laragon\www\pozadmin\app\Http\Controllers\VidyObjectovController.php:194
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: add_keys_fields", "C:\laragon\www\pozadmin\app\Http\Controllers\VidyObjectovController.php", [Object(App\Http\Requests\VidyObjectovUpdateRequest), Object(App\Models\VidyObjectov)])

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.8.3
