### ISSUE TITLE
[SUGGESTION] For the migration list and shema editor, you also need to add a search field, as in the lists of projects and applications

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#109]
For the migration list and shema editor, you also need to add a search field, as in the lists of projects and applications

**Comment by TiagoSilvaPereira** [comment]
Thank you for your suggestion

**Comment by TiagoSilvaPereira** [comment]
Search added for migrations page. Search for Schema is coming soon.
