### ISSUE TITLE
[BUG] Jetstream Input fields style

### ISSUE THREAD

**Issue by Talbourdet** [TiagoSilvaPereira/vemto-issues#114]
**Describe the bug**
When building a new project with Jetstream, css does not apply correctly and is mainly noticed on the design of forms and in particular of input fields.

**To Reproduce**
1. Build a new project with Vemto
2. Select Jetstream ui template and Tailwind css framework
3. Normally configure the rest of the project
4. Run the app

**Expected behavior**
From the login page we notice that the input fields of Jetstream do not have their normal appearance. The forms generated by Vemto are normal.

**Screenshots**
![Login pages
](https://media.discordapp.net/attachments/756200910996373621/831810484893384714/unknown.png?width=960&height=439)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Google Chrome Version 89.0.4389.114 (Build officiel) (x86_64)
 - Version Vemto 0.8.2

**Additional context**
I think the problem can be solved by adding the plugin below in "tailwind.config.js"

`plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],`

**Comment by TiagoSilvaPereira** [comment]
Hi @Talbourdet thank you very much for reporting, I'll fix this bug ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
