### ISSUE TITLE
[BUG] Vemto does not recognize my PATH variables

### ISSUE THREAD

**Issue by muharremkackin** [TiagoSilvaPereira/vemto-issues#115]
**Describe the bug**
Hello dear developers, i tried generate my test laravel application from vemto. But it always crash when it need to use and says;

"Sorry, Vemto requires composer installed in your system. Please check if composer is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page"

I already have all PHP development and Node needs and I added them to PATH

**To Reproduce**
1. Go to 'Generate Code'
2. Click on 'Generate Button'
3. See Starting code generation!
4. See error; Command failed: "composer --version"

**Expected behavior**
I think it should generate a Laravel application with what I created in Vemto

**Desktop :**
 - OS: Windows 10
 - PHP 8.0.x
 - Composer 2.0.x
 - Node 14.x.x
 - Vemto
 - Version [0.8.2]

**Comment by TiagoSilvaPereira** [comment]
Hi @muharremkackin please try restarting your computer. If Vemto still does not recognize your binaries on PATH, you can add the path to the Vemto environment variables. Reference here: https://vemto.app/docs/0.x/configuration

Cheers

**Comment by muharremkackin** [comment]
It worked alright when I added paths to setting, thank you!

**Comment by asharekh** [comment]
Hi, 

i have the same issue, followed all guides and tips, still not working

error : 

`Starting code generation!
Checking php
Checking composer
Command failed: /usr/local/bin/composer --version /bin/sh: /usr/local/bin/composer: is a directory
Command failed: /usr/local/bin/composer --version /bin/sh: /usr/local/bin/composer: is a directory
Sorry, Vemto requires composer installed in your system. Please check if composer is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page
Error: Sorry, Vemto requires composer installed in your system. Please check if composer is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page at p.checkDependency (app://./js/chunk-common.9e74499f.js:1:29099) at Xt.checkDependencies (app://./js/generator.f8b0147f.js:1:63134) at Xt.start (app://./js/generator.f8b0147f.js:1:62232) at EventEmitter. (app://./js/generator.f8b0147f.js:1:65369) at EventEmitter.emit (events.js:210:5) at Object.onMessage (electron/js2c/renderer_init.js:2243:16)`

**Comment by TiagoSilvaPereira** [comment]
Hi @asharekh as you can see on your error message:

```
/bin/sh: /usr/local/bin/composer: is a directory
```

It means that your composer binary is not inside the /usr/local/bin directory. Maybe it is on /usr/local/bin/composer?

You need to set the exact folder that contains de composer binary.
