### ISSUE TITLE
[BUG] When enabling team in the Jetstream configuration, an error message is displayed

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#116]
When enabling team in the Jetstream configuration, an error message is displayed

![nnn_B00001_001](https://user-images.githubusercontent.com/80303996/115100954-9e881400-9f6a-11eb-8536-cda750a3433e.jpg)

![nnn_B00001_002](https://user-images.githubusercontent.com/80303996/115100956-a34cc800-9f6a-11eb-80e4-10164e1c105a.jpg)

**Comment by TiagoSilvaPereira** [comment]
@StasKoun2 thank you for reporting, I'll check it soon

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 I just checked here and it happens because, to use Jestream Teams after the installation, you need to run this command first:

```
