### ISSUE TITLE
[BUG] The search does not support non-Latin letters (for example, Russian)

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#117]
The search does not support non-Latin letters (for example, Russian)

![nnn_B_001](https://user-images.githubusercontent.com/80303996/115101036-3f76cf00-9f6b-11eb-97ba-6453978c505e.jpg)

![nnn_B_002](https://user-images.githubusercontent.com/80303996/115101039-40a7fc00-9f6b-11eb-80c6-02668cff7a01.jpg)

![nnn_B_003](https://user-images.githubusercontent.com/80303996/115101040-41409280-9f6b-11eb-8d2e-27b417df7823.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 I'm closing as it is not a Vemto bug... please try adding your collation settings on .env, as you can see here: https://seegatesite.com/how-to-solve-problems-illegal-mix-of-collations-latin1_swedish_ciimplicit-in-laravel/
