### ISSUE TITLE
[BUG] faker->mobileNumber

### ISSUE THREAD

**Issue by threeel** [TiagoSilvaPereira/vemto-issues#119]
When you create a model with an attribute ```mobile``` will generate a factory with the ```'mobile' => $this->faker->mobileNumber,```
on ```php artisan migrate:fresh --seed``` you get an error that mobileNumber doesnt exist
when you replace it with phoneNumber it works as expected

**Comment by TiagoSilvaPereira** [comment]
@threeel thank you for reporting, I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
