### ISSUE TITLE
Duplicate a Project

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#121]
I would be nice to duplicate a project.

many of my apps have core functionality (teams, companies, tags etc)

it would be nice to have a project containing all the common things that i could duplicate when i start a new app.

maybe this is part of import/export?

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj thank you for your suggestion... I'm closing here as it is already on the roadmap: https://trello.com/b/0MTU9Vyq/vemto-roadmap
