### ISSUE TITLE
[SUGGESTION] Add Metadata options for path to php binary and php.ini file

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#122]
I have several different versions of php installed on my system, it would be great if i could specify which php binary to use for app generation and also which php.ini file to use

I don't always have full control over the final hosting for an app so sometimes it needs to be generated using php 7.3, 7.4 or 8.0.x

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj thank you for your suggestion... For Vemto, it doesn't matter very much what version of PHP you are using to generate, as it is a configuration more related to Laravel than Vemto. So, I'd recommend you changing these configurations on your Development environment and changing it using your command line editor when necessary.

Best regards,
Tiago
