### ISSUE TITLE
[BUG] incorrect belongs to many table name used in generated migration

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#125]
**Describe the bug**
I have Models:
DataObject
EventSourceEvent

There is a Belongs To Many
<img width="1363" alt="Screen Shot 2021-05-01 at 22 48 34" src="https://user-images.githubusercontent.com/4245429/116795906-2ffd9700-aad0-11eb-853e-43d6c940ba81.png">
 relationship

The table name for the pivot table in Vemto shows as data_objects_event_source_event

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('data_objects_event_source_events', function (
            Blueprint $table
        ) {
            $table->unsignedBigInteger('event_source_event_id');
            $table->unsignedBigInteger('data_object_id');
        });
    }

The migration is generated has the table name data_objects_event_source_events

I believe this may have occurred as the model names used to be DataObjects and EventSourceEvents

The generated project has been deleted and freshly generated so there must be some data inside the project that has not updated.

Happy to send vemto project and generated files privately but cannot post publicly here

**Comment by deanlj** [comment]
This defo seems to be related to models being renamed.

New belongs to many pivot tables are ok.

**Comment by deanlj** [comment]
Looks like the pivotOriginalName in the parent entity json file is not getting updated and neither is the table name in the pivot table entity
<img width="503" alt="Screen Shot 2021-05-02 at 01 30 53" src="https://user-images.githubusercontent.com/4245429/116798315-241ccf80-aae6-11eb-8df2-da4ca33eb4e3.png">

{
    "projectId": 1,
    "name": "workflow_condition_workflow_step",
    "type": "table",
    **"table": "workflow_conditions_workflow_steps",**
    "plural": "",
    "top": "843px",
    "left": "-309px",
    "pivot": true,
    "softDeletes": false,
    "timestamps": false,
    "migrationName": "2021_04_22_000009_create_workflow_condition_workflow_step_table.php",
    "foreignsMigrationName": "2021_04_22_009008_add_foreigns_to_workflow_condition_workflow_step_table.php",
    "id": 45,
    "createdAt": "2021-04-28 17:59:20",
    "updatedAt": "2021-05-02 01:07:54"
}

{
    "modelId": 5,
    "pivotId": 45,
    "inverseId": 40,
    "localModelId": 43,
    "modelKeyId": 199,
    "localModelKeyId": 200,
    "name": "workflowSteps",
    "type": "belongsToMany",
    **"pivotOriginalName": "workflow_conditions_workflow_steps",**
    "modelKeyOriginalName": "workflow_step_id",
    "localModelKeyOriginalName": "workflow_condition_id",
    "hasApi": true,
    "id": 39,
    "createdAt": "2021-04-28 17:59:20",
    "updatedAt": "2021-05-01 19:42:36"
}

pivot table name was updated in schema editor to  workflow_condition_workflow_step

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj I'll check this bug soon

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
