### ISSUE TITLE
[BUG] Changing a model name and table name does not update migration file names

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#126]
**Describe the bug**
After changing a model name and the table name in the schema editor, the migration file names in Project Settings -> Migrations does not get updated even though the generated Class name in the migration does

**To Reproduce**
1. Create a model in the Schema editor with the name ConnectedAccountStats
2. Generate the app 
3. Change the name of the model to ConnectedAccountMetrics, change the table name in the schema editor to connected_account_metrics
4. In Project Settings -> Migrations, the file name for the model is still 2021_04_22_000003_create_connected_account_stats_table.php but should have changed to 2021_04_22_000003_create_connected_account_metrics_table.php
5. Generate the app
6. the file 2021_04_22_000003_create_connected_account_stats_table.php is generated but the classname in the file is CreateConnectedAccountMetrics so causes an error when running migrations.

**Expected behavior**
When a model name and table name is changed in the schema editor, the migration file name should change so the migration class name matches.

If the app is generated again the original migration file should be replaced with the new file.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Brave
 - Version MacOS Mojave

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
