### ISSUE TITLE
[SUGGESTION] Adding new entities in the Schema Editor should be placed in the current visible area

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#128]
**Is your feature request related to a problem? Please describe.**
When adding new entities (models or tables) or creating a Belongs To Many relationship the new entity is placed a the upper right of the schema editor.

When the app has a large number of entities you have to scroll up and right to find it and then do multiple drag and drops to bring it down to where  you want it.
 
**Describe the solution you'd like**
If i have a large diagram that doesn't fit on screen at once I want the new entity to be placed in the currently visible region of the diagram

**Describe alternatives you've considered**
n/a

**Additional context**
n/

**Comment by TiagoSilvaPereira** [comment]
@deanlj thank you for your suggestion, it is already on our Task list

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj I'm closing here as it is already on my plans and probably will come on the next version
