### ISSUE TITLE
[BUG] Create Table Error

### ISSUE THREAD

**Issue by JPOyarzunA** [TiagoSilvaPereira/vemto-issues#129]
After adding an Entity and manually change the Table name the file create_[Table_Name]_table.php doesn't change his name and fails to create the table when migrate. I had to manually change the file name to pass the migration.

**Comment by TiagoSilvaPereira** [comment]
Hi @JPOyarzunA thank you for reporting... I'm closing here as there is already an open issue to handle this problem: https://github.com/TiagoSilvaPereira/vemto-issues/issues/126
