### ISSUE TITLE
[BUG] window.changeCase[e] is not a function when generating translations

### ISSUE THREAD

**Issue by opizarrosilva** [TiagoSilvaPereira/vemto-issues#132]
**Describe the bug**
En el log aparece:
Generating CRUD translations...
window.changeCase[e] is not a function

**To Reproduce**
1. Go to 'Generate'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83740682/117576878-78f7b180-b0b5-11eb-9360-3581e66280ac.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS 2010
 - Browser: CHROME
 - Versión 90.0.4430.93 (Build oficial) (64 bits)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TiagoSilvaPereira** [comment]
Hi @opizarrosilva could you please share your Schema?

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
