### ISSUE TITLE
[ENHANCEMENT] Unique key for field options

### ISSUE THREAD

**Issue by daryledesilva** [TiagoSilvaPereira/vemto-issues#15]
Please check this screenshot for quick explanation

![image](https://user-images.githubusercontent.com/4393436/94981738-502f9c80-0567-11eb-9249-3ea425d8e978.png)

**Comment by TiagoSilvaPereira** [comment]
Thank you @daryledesilva for your suggestion... I'll add this option after changing the database layer on issue #10

**Comment by TiagoSilvaPereira** [comment]
@daryledesilva I just added this enhancement on **0.5.10**. Thanks
