### ISSUE TITLE
By creating entity

### ISSUE THREAD

**Issue by almiro75** [TiagoSilvaPereira/vemto-issues#151]
```
RangeError: Maximum call stack size exceeded
    at a.executeRelationship (app://./js/chunk-vendors.73ccc855.js:57:5628)
    at Object.__get [as get] (app://./js/chunk-vendors.73ccc855.js:57:2442)
    at Proxy.value (app://./js/chunk-common.0bd19850.js:1:49895)
    at Function.value (app://./js/chunk-common.0bd19850.js:1:51306)
    at Proxy.update (app://./js/chunk-vendors.73ccc855.js:57:3999)
    at Proxy.save (app://./js/chunk-vendors.73ccc855.js:57:3501)
    at Proxy.value (app://./js/chunk-common.0bd19850.js:1:50052)
    at Function.value (app://./js/chunk-common.0bd19850.js:1:51306)
    at Proxy.update (app://./js/chunk-vendors.73ccc855.js:57:3999)
    at Proxy.save (app://./js/chunk-vendors.73ccc855.js:57:3501)
```

---

vemto 0.9.3
Electron 8.5.5
win32 6.3.9600
Locale: de

**Comment by TiagoSilvaPereira** [comment]
Hi @biogasregister thank you for reporting. Could you please share more details, like:

- A screenshot of your Schema
- When the problem happens?
- what can I do to reproduce that?

**Comment by biogasregister** [comment]
I can't reproduce it again.. i just started creating new entity then it happens!
the shema is here: https://prnt.sc/132z4f8

**Comment by TiagoSilvaPereira** [comment]
Hi @biogasregister I'll try to reproduce here. But seems you have some issues with your Schema. When you create a Model (Course for example), it is not necessary to create the table. I recommend working always with models, as on rare occasions when you need a table, as in a Pivot table, Vemto will take care of creating it automatically.

Do you remember what model or table throws the error when creating it?

**Comment by biogasregister** [comment]
Hi Tiago, honestly - i don't remember this, but it think it was by creating a Model - so its the only one i have for now.
Thank you for the info allways, but meanwhile i've got an error by generating the code.. It seems is a configuration issue with npm.
Here the Screenshot: https://prnt.sc/132ztl9

**Comment by TiagoSilvaPereira** [comment]
Hi @almiro75 someone had a similar problem with npm and windows recently... could you please try reinstalling nodejs and npm?

**Comment by almiro75** [comment]
Hi Tiago, i allready reinstalled Node.js, also Vemto to, restart the computer but the problem still there as you can see in screenshot: https://prnt.sc/136ogtr

**Comment by TiagoSilvaPereira** [comment]
Hi @almiro75 what happens when you execute the exact same code on your terminal?

**Comment by almiro75** [comment]
Hi Tiago, what excatly do you mean to executing in terminal? ... so the next error is here, as you can see in the screenshot: https://prnt.sc/138jbfq

**Comment by almiro75** [comment]
maybe found a solution, but please keep kalm, don't know if this working for others... i wrote to a fend this:

i found a quick and dirty solution for my problem, if you need to know. I copied the node_modules folder to VemtoRoaming folder in this folder and it seems to  working.. happy if fits.. otherwise pleased to teach me..

**Comment by TiagoSilvaPereira** [comment]
Hi, @almiro75 could you please share a PrintScreen of Vemto settings and a PrintScreen showing each of the folders listed there?

![image](https://user-images.githubusercontent.com/11933789/119352220-cbb99780-bc77-11eb-8bb1-36936b3c8338.png)

You can try following this documentation to configure the Vemto settings: https://vemto.app/docs/0.x/configuration

**Comment by TiagoSilvaPereira** [comment]
Closed due to inactivity
