### ISSUE TITLE
Master Detail Errors

### ISSUE THREAD

**Issue by graham-ch** [TiagoSilvaPereira/vemto-issues#153]
**Describe the bug**
On master detail pages the show (master) page does not show the detail records, the edit (master) page results in an error

ParseError
syntax error, unexpected 'Plate' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) (View: /Users/G/code/master_detail/resources/views/app/plates/edit.blade.php)

**To Reproduce**
Create a very simple schema. Consisting of 3 models, users, plates, foods. The plate and food models have 1 field each (title).

A user hasMany plates, a plate hasMany foods.

![screen129](https://user-images.githubusercontent.com/4248589/119490899-42789280-bd55-11eb-8cdd-c81e4137705f.png)

**Expected behaviour**

No errors.

**Screenshots**

![screen130](https://user-images.githubusercontent.com/4248589/119490922-486e7380-bd55-11eb-9995-ee11e8582e1e.png)

![screen131](https://user-images.githubusercontent.com/4248589/119490946-4dcbbe00-bd55-11eb-8aaa-33895f321d85.png)

![screen132](https://user-images.githubusercontent.com/4248589/119491022-620fbb00-bd55-11eb-873a-609fb813f713.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser All Browsers

**Additional context**
Everything left at default to test the error other than disabling turbolinks.

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch I needed to make a little adjustment on the Food model because Vemto generates the plural as 'foods', but Laravel considers the plural as 'food', so the migrations don't run. But after fixing it, the application is running well:

![image](https://user-images.githubusercontent.com/11933789/119508533-320ceb80-bd46-11eb-9e50-8f48c3892c12.png)

![image](https://user-images.githubusercontent.com/11933789/119508475-28838380-bd46-11eb-902b-ccfcbb0fa1f5.png)

**Comment by graham-ch** [comment]
Thanks Tiago.

FYI I had the same problem with another schema.

users, folders, videos

Would that be the same issue/fix do you think?

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch I'll check with this other schema

**Comment by TiagoSilvaPereira** [comment]
It worked without modifications :thinking: 

I'll try to understand what is happening in your case.

![image](https://user-images.githubusercontent.com/11933789/119512037-57e7bf80-bd49-11eb-9a5b-2f602897b0bc.png)

**Comment by TiagoSilvaPereira** [comment]
@graham-ch what PHP version are you using?

**Comment by TiagoSilvaPereira** [comment]
@graham-ch yes, the problem is the PHP version... the class property types were implemented on PHP 7.4... please upgrade your PHP and the problem will be gone.

Cheers
