### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ballesta** [TiagoSilvaPereira/vemto-issues#157]
**Describe the bug**
Under Ubuntu, installed new ubuntu 21.04 version from scratch with a new disk.
Installed Vemto
Upon entering my licence, vemto say that it is already in use on anoter computer.
I tried to revoke the licence with out success, it still says that my licence is in use.
May be Ishould wair for some time for revocation is taken in accounr?
**Desktop (please complete the following information):**
 
- OS: Ubuntu 21.04

Best regards 
Bernard

**Comment by TiagoSilvaPereira** [comment]
Hi @ballesta you need to vacate the license on the Vemto dashboard: https://vemto.app/home (just click in the *Vacate* button to be able to use the license on another computer)
