### ISSUE TITLE
Input field on modal cannot be filled

### ISSUE THREAD

**Issue by 3ch3r46** [TiagoSilvaPereira/vemto-issues#158]
**Describe the bug**
If remove some field or some entity, the input field on modal like modal Add Entity cannot be filled.

**To Reproduce**
1. Go to 'Schema Editor'
2. Click on 'Add Entity'
3. Click on 'create'
4. remove the entity
5. Click on 'Add Entity'
3. Fill the input
4. See error: the cursor not focus on input field.

**Expected behavior**
i think this happen if the confirm alert shown.

**Comment by TiagoSilvaPereira** [comment]
@3ch3r46 thank you for reporting, I'll fix it ASAP

**Comment by TiagoSilvaPereira** [comment]
Hi @3ch3r46 I tried to reproduce the error, but it doesn't happen here... could you please record a short video showing the process you are doing before throwing the error? Thanks

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.7
