### ISSUE TITLE
[BUG] Error in windows when reordering fields under entity options

### ISSUE THREAD

**Issue by daryledesilva** [TiagoSilvaPereira/vemto-issues#16]
```
TypeError: Cannot read property 'fill' of undefined
    at app://./js/project_schema.582451ce.js:1:35619
```

---

vemto 0.4.15
Electron 8.5.0
win32 10.0.18362
Locale: en-GB

**Comment by TiagoSilvaPereira** [comment]
Thanks for reporting sir... Could you please send me a screenshot of your fields so I can check what is happening?)

**Comment by daryledesilva** [comment]
ah yeah sorry i forgot to attach the screenshot. anyway i'll try to reproduce this issue again but no promises if i can provide the screenshot 👍

**Comment by TiagoSilvaPereira** [comment]
Hi, @daryledesilva I think it will don't happen on 0.5.2... I'm closing for now, but feel free to comment here if the problem happens again. Have a nice day, thanks!
