### ISSUE TITLE
[BUG].env file not generated

### ISSUE THREAD

**Issue by ballesta** [TiagoSilvaPereira/vemto-issues#161]
**Describe the bug**
During code generation, the .env file is not generated.
The reason invoked is that the .env.example is not found

**To Reproduce**
Generate code replacing all files

**Expected behavior**
Should generate .env file

**Screenshots**
Trace of Vemto startup and code generation in terminal:
(My comments inside trace are surrounded by "<=== comment ===>")

============================================================================
./vemto-0.9.3.AppImage 
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
10:21:35.698 › Checking for update
Failed to register app protocol Error: The scheme has been registered
    at Object.<anonymous> (electron/js2c/browser_init.js:2767:47)
    at y (/tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:182114)
    at /tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:183266
    at x (/tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:183346)
    at App.<anonymous> (/tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:183616)
    at App.emit (events.js:215:7)
(node:4508) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:4508) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
10:21:36.814 › Update for version 0.9.3 is not available (latest version: 0.9.3, downgrade is disallowed).
10:21:36.817 › checkForUpdatesAndNotify called, downloadPromise is null
Failed to register app protocol Error: The scheme has been registered
    at Object.<anonymous> (electron/js2c/browser_init.js:2767:47)
    at y (/tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:182114)
    at IpcMainImpl.<anonymous> (/tmp/.mount_vemto-8LmFtL/resources/app.asar/background.js:3:185509)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
    at WebContents.emit (events.js:210:5)
(node:4508) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
<b>Starting code generation!</b>
Checking php
Checking composer
Checking git
Checking npm
<=== .env not generated ===>
<b>.env.example</b> file not found. Skipping .env file generation
<=== .env not generated ===>
Adding "Policy Guessing"...
Writing File: /home/bernard/www/data_dictionnary/app/Providers/AuthServiceProvider.php
Gerenating App Service Provider...
Writing File: /home/bernard/www/data_dictionnary/app/Providers/AppServiceProvider.php
Changing authentication settings...
Writing File: /home/bernard/www/data_dictionnary/config/auth.php
Starting CRUD generation...

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser Firefox
 - Version

Best regards
Bernard

**Comment by TiagoSilvaPereira** [comment]
Hi @ballesta could you please check if all commands are checked for first code generation?

![image](https://user-images.githubusercontent.com/11933789/120661066-52335d80-c45e-11eb-83ec-a6cd6d6673d8.png)

**Comment by TiagoSilvaPereira** [comment]
If **git clone ...** is disabled, the base Laravel code will not be downloaded, and Vemto will generate only application logic files

**Comment by ballesta** [comment]
I understand that it is mandatory to generate code to git repository.

**Comment by TiagoSilvaPereira** [comment]
Hi @ballesta this option is always checked by default, you probably unchecked it accidentally... but it is not mandatory, some people just want to generate the project code to replace it, and not the complete project. That is the reason that you can disable running **git clone** when necessary (but for default scenarios, keep it checked).

**Comment by ballesta** [comment]
Thank you Tiago.

This lead to 2 more questions:

1:Could you tell me where is stored the application schema (entities,
fields, ....)?

2:Where is stored the git hub repository?

3:How do I track the manual modifications to generated code?

Best regards
Bernard

**Comment by TiagoSilvaPereira** [comment]
Hi @ballesta 

**1:Could you tell me where is stored the application schema (entities, fields, ....)?**

All the project data is stored on the %APP_DATA%/vemto folder, inside the storage/reladb subfolder (RelaDB is the database that Vemto uses to store the data). 

**2:Where is stored the git hub repository?**

Vemto doesn't store the git repository. It only uses the [Laravel default repository](https://github.com/laravel/laravel) to clone and start the project. If you want to upload your code to a git repository (which I strongly recommend), it is necessary to manually run the git commands on your project folder (Vemto doesn't use git for anything more than cloning the base project, so it doesn't interfere with your git usage, you can use both git and vemto without problems) 

**3:How do I track the manual modifications to generated code?**

Vemto automatically tracks manual modifications. Whenever you change a file generated by vemto, it will skip generating it and will show you the difference, so you can decide between keeping, overwriting, or copying/pasting the generated code.

Cheers
