### ISSUE TITLE
[BUG] Master Details not working

### ISSUE THREAD

**Issue by hossam-hani** [TiagoSilvaPereira/vemto-issues#162]
**Describe the bug**
I create a product model with image model | product hasMany relation and when I add master details nothing happened after generating the code 

![image](https://user-images.githubusercontent.com/42097342/120658211-866e4480-c485-11eb-9d77-ec092cc023b1.png)
![image](https://user-images.githubusercontent.com/42097342/120658283-94bc6080-c485-11eb-9b95-0ca20df62745.png)
![image](https://user-images.githubusercontent.com/42097342/120658469-c1707800-c485-11eb-8571-4d28fcfc2ad3.png)
![image](https://user-images.githubusercontent.com/42097342/120658531-ce8d6700-c485-11eb-845d-9b4ad982dc61.png)

Windows version | laravel 8

**Comment by TiagoSilvaPereira** [comment]
Hi @hossam-hani thank you for calling me here... it is not a Vemto bug, you just need to upgrade your PHP version. It happens because the generated code uses PHP Typed Class Properties, and it is only supported for PHP 7.4+

Best regards,
Tiago Rodrigues

**Comment by TiagoSilvaPereira** [comment]
@hossam-hani only a tip: if you can't upgrade to PHP 7.4, you can just remove the Typed Properties from your components. For example:

Change this:

```php 
public Product $product;
```

To this:

```
public $product;
```

**Comment by hossam-hani** [comment]
still same issue when upgrade to 7,4

**Comment by hossam-hani** [comment]
[image: image.png]
still same issue after upgrade php version

**Comment by TiagoSilvaPereira** [comment]
Hi @hossam-hani please try running your code manually from the terminal and check if it is running with PHP 7.4+... this problem is specific for PHP 7.3<, so it is likely that Vemto is not running with the correct PHP version (maybe it is not correctly set on the Environment Variables, or Vemto is loading it from the old path).

You can try directly setting the PHP 7.4 path on Vemto environment settings, as you can see here: https://vemto.app/docs/0.x/configuration

**Comment by hossam-hani** [comment]
i did it already , change the path from your settings
![image](https://user-images.githubusercontent.com/42097342/120664317-21b5e880-c48b-11eb-822e-5a10b2bfdf88.png)

**Comment by hossam-hani** [comment]
![image](https://user-images.githubusercontent.com/42097342/120664548-4f029680-c48b-11eb-8c5f-367de4a138de.png)

**Comment by hossam-hani** [comment]
![image](https://user-images.githubusercontent.com/42097342/120665051-bb7d9580-c48b-11eb-88a2-663880c31a53.png)
compile from the new version

**Comment by TiagoSilvaPereira** [comment]
Hi @hossam-hani this is another error, as you can see in the error message... 

```
Cannot redeclare $image
```

It is happening because your model is called *Image*, and you also have a field called *image* in the same table... please use a different name, for example:

- Model Image with a field file
- Model Photo with a field image

Or, if you want to keep the name Image and the field as image, you can change the code manually after the generation.

Best regards,
Tiago

**Comment by hossam-hani** [comment]
the UI not updated Tiago !

**Comment by TiagoSilvaPereira** [comment]
@TiagoSilvaPereira sorry I did not understand

**Comment by hossam-hani** [comment]
![image](https://user-images.githubusercontent.com/42097342/120666250-ba009d00-c48c-11eb-899c-5e0466e863ce.png)
where is the mater details in UI ?

**Comment by TiagoSilvaPereira** [comment]
Did you created the item? Master-Detail show after creating the item

**Comment by TiagoSilvaPereira** [comment]
Hi @hossam-hani did it worked?

**Comment by hossam-hani** [comment]
![image](https://user-images.githubusercontent.com/42097342/120667623-f5e83200-c48d-11eb-8e9c-be4bcd278da2.png)
 can't acess the project now , maybe I should try start new project and follow your steps

**Comment by hossam-hani** [comment]
can we take a online meeting ?
[image: image.png]

>

**Comment by hossam-hani** [comment]
i'm stuck here

**Comment by hossam-hani** [comment]
[image: image.png]

i'm start new project and face same issue :"(

**Comment by hossam-hani** [comment]
![image](https://user-images.githubusercontent.com/42097342/120676402-45caf700-c496-11eb-8baf-d7ab08d2034a.png)
i re-created the project and when start use the feature no image uploaded :"(

**Comment by TiagoSilvaPereira** [comment]
@hossam-hani is your storage linked to the public folder?

**Comment by hossam-hani** [comment]
Okay everything right now works fine the problem with validation parameters and I change it to image, and now everything worked fine 

and I use it you tip and the models work fine now, thanks man you doing a **Amazing** work

**Comment by TiagoSilvaPereira** [comment]
@hossam-hani amazing to know it :pray:

**Comment by TiagoSilvaPereira** [comment]
Related to #153
