### ISSUE TITLE
Change the collection name and table after changing the model name

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#167]
When you change the model name, the collection name and tables are not updated.

![nnn_9000100](https://user-images.githubusercontent.com/80303996/120821923-12fd2d80-c580-11eb-8985-bda1f5ae1e93.jpg)

**Comment by StasKoun2** [comment]
And you need to update all the other dependencies on the model name : relationships, and so on .....

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 I'll add a confirmation to ask if you want to regenerate the collection and table, and relationships after changing a model name (sometimes it is not the desired behavior, so it needs to be optional).

**Comment by TiagoSilvaPereira** [comment]
Partially fixed on 0.9.7

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
