### ISSUE TITLE
Cambiar licencia de computador

### ISSUE THREAD

**Issue by VedataGroup** [TiagoSilvaPereira/vemto-issues#168]
Voy a cambiar mi computador y quiero llevar la licencia al nuevo computador, ¿cómo pudeo hacerlo?

**Comment by TiagoSilvaPereira** [comment]
Hi @VedataGroup you can just Revoke the license from Vemto on your previous computer, or **Vacate** the license from your Vemto Dashboard: https://vemto.app/home
