### ISSUE TITLE
Custom field on show page

### ISSUE THREAD

**Issue by alessandrodorazio** [TiagoSilvaPereira/vemto-issues#169]
Hi,
I'm using the trial version of the software, and I want to show how many items belong to a category on the show page of the category.

I haven't understood how I can do this, because if I use a standalone computed text, I can see only in the index page, but not on the show page. It is possible to do or I have to edit the code?

Thanks for the support

**Comment by TiagoSilvaPereira** [comment]
Hi @alessandrodorazio yes, it would be necessary to edit the code, as computed inputs work only on lists and index pages for now... but I want to add support for show pages too
