### ISSUE TITLE
BUG. redeclare in livewire

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#171]
![pp_001](https://user-images.githubusercontent.com/80303996/122652428-01637a80-d169-11eb-8e86-ff09a5bba67f.jpg)
![pp_002](https://user-images.githubusercontent.com/80303996/122652429-0294a780-d169-11eb-9d31-977d76187c37.jpg)
![pp_003](https://user-images.githubusercontent.com/80303996/122652430-032d3e00-d169-11eb-8265-8ceefe6f3338.jpg)
![pp_007](https://user-images.githubusercontent.com/80303996/122652431-03c5d480-d169-11eb-8bba-869260878d62.jpg)
![pp_008](https://user-images.githubusercontent.com/80303996/122652432-045e6b00-d169-11eb-8319-3ab87f06fb49.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.7
