### ISSUE TITLE
Bug. dublicate in controllers

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#172]
![ppp_001](https://user-images.githubusercontent.com/80303996/122652613-efcea280-d169-11eb-8be2-f02438ff1918.jpg)
![ppp_002](https://user-images.githubusercontent.com/80303996/122652780-ce21eb00-d16a-11eb-92a5-70cbeb95bec6.jpg)
![ppp_003](https://user-images.githubusercontent.com/80303996/122652614-f0ffcf80-d169-11eb-8c67-66de81db5e93.jpg)
![ppp_007](https://user-images.githubusercontent.com/80303996/122652615-f1986600-d169-11eb-87df-724a8cf40a04.jpg)
![ppp_008](https://user-images.githubusercontent.com/80303996/122652616-f230fc80-d169-11eb-8c6f-d82c94961185.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.7
