### ISSUE TITLE
Date field incorrectly formatted on Master Detail

### ISSUE THREAD

**Issue by AlexJames-Dev** [TiagoSilvaPereira/vemto-issues#173]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
The creation modal on the master details does not seem to have it's date field formatted correctly

**To Reproduce**
1. Create two models, X and Y with X having a hasMany relationship to Y; and model Y containing a Date Field
2. Add a master detail form to the CRUD page for X
3. Load application and navigate to App X
4. Create a Record for X
5. Click New, on the master detail on that record
6. The modal will pop up, attempt to add in a date, it will fail with a console error relating to incorrect formatting

**Expected behavior**
Date should be able to be input

**Screenshots**
Video of issue in action: [Video](https://streamable.com/sg7wi1)

**Desktop (please complete the following information):**
 - OS: OSX 
 - Browser: Microsoft Edge Chromium
 - 11.4 (20F71)

**Comment by TiagoSilvaPereira** [comment]
Hi @AlexJames-Dev thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.7
