### ISSUE TITLE
Periods in directory names are being replaced with underscores when generating code

### ISSUE THREAD

**Issue by RPJamie** [TiagoSilvaPereira/vemto-issues#174]
**Describe the bug**
Directories for git repositories with periods in their name, when running generate, are converted into underscores.
The results are a new directory is created with the generated files.

eg:
Source directory path,  `/home/some.git.project`
Generated files creates, `/home/some_git_project`

**To Reproduce**
* In Vemto, under `Project Settings` set `Name` to a directory that has periods in it's name.
* Run the Generate action

**Expected behavior**
The generated code runs in the exact specified directory name without replacing characters with an underscore.

**Desktop (please complete the following information):**
 - OS: macOS (Big Sur)
 - Version: 0.9.4 (0.9.4)

**Comment by TiagoSilvaPereira** [comment]
Hi @RPJamie thank you for reporting, I'll check it

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.11
