### ISSUE TITLE
[BUG] Space in project path causes error in Windows

### ISSUE THREAD

**Issue by computer-logix** [TiagoSilvaPereira/vemto-issues#18]
If you start a project with a space in it the 'git clone' command fails due to too many arguments on window.
In this case I used the path **_c:\Downloads\test project_**

![space in project name](https://user-images.githubusercontent.com/19731113/97700062-94885c80-1a81-11eb-8030-f6b60aa45994.png)

**Comment by IgorPC** [comment]
![image](https://user-images.githubusercontent.com/42573469/97714691-3d45b480-1aa0-11eb-8342-07ec62265f39.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @computer-logix thank you for opening the issue, I'll fix this soon

**Comment by computer-logix** [comment]
> Hi @computer-logix thank you for opening the issue, I'll fix this soon

Not a problem.   I don't normally uses spaces in any paths but it was the first problem that popped up for me when testing.

I purchased a lifetime business license because I can see this as being a great timesaver if you manage to accomplish your roadmap of features.  Great work!

**Comment by TiagoSilvaPereira** [comment]
@computer-logix thank you very much for your support

**Comment by IgorPC** [comment]
Hello @TiagoSilvaPereira, I believe my problem is the same as @computer-logix. I await the correction of this bug. But I congratulate you for the great job.

**Comment by TiagoSilvaPereira** [comment]
@computer-logix @IgorPC thank you for reporting it... I just fixed it on 0.5.4 (the update is automatic, but you can download it on the site too). 

Cheers
