### ISSUE TITLE
Vemto does not find 'npm'.

### ISSUE THREAD

**Issue by josefo727** [TiagoSilvaPereira/vemto-issues#181]
Greetings @TiagoSilvaPereira . . .

I have problems running **_Generate_** in Vemto, it does not recognize or cannot find the **npm** file.

![image](https://user-images.githubusercontent.com/39111029/123874089-31dfad00-d8fd-11eb-8ce7-3f64bde4b9c4.png)

**My current setup:**

![image](https://user-images.githubusercontent.com/39111029/123874227-6fdcd100-d8fd-11eb-9f99-f686c6ab327b.png)

If I configure the path in setting (Debian 10):

![image](https://user-images.githubusercontent.com/39111029/123874527-f2659080-d8fd-11eb-9bfe-14f2d6e5d118.png)

I get:

![image](https://user-images.githubusercontent.com/39111029/123874656-1fb23e80-d8fe-11eb-980f-d38df3c91d12.png)

Thank you very much in advance for the support...

**Comment by josefo727** [comment]
Greetings again @TiagoSilvaPereira . . .

I was able to solve by creating a symbolic link in this way, it can be closed, thank you very much.

`sudo ln -s /home/josefo/.config/nvm/versions/node/v14.15.5/bin/node /usr/bin/node`

**Comment by TiagoSilvaPereira** [comment]
Hi @josefo727 thank you for posting your solution
