### ISSUE TITLE
`composer.json` and `package.json` not written during generation

### ISSUE THREAD

**Issue by 949mac** [TiagoSilvaPereira/vemto-issues#182]
Generating the application seems to omit some core files.

![image](https://user-images.githubusercontent.com/23151962/124032330-4bd8c880-d9ad-11eb-9597-1c5583689b3c.png)

**Warnings Received**

![image](https://user-images.githubusercontent.com/23151962/124032179-16cc7600-d9ad-11eb-8375-2e63be39b972.png)

![image](https://user-images.githubusercontent.com/23151962/124032239-2946af80-d9ad-11eb-9ab3-c97085c7e5e1.png)

![image](https://user-images.githubusercontent.com/23151962/124032249-2cda3680-d9ad-11eb-8e06-c1f73b578bf7.png)

**If requested**

I can provide a project export file via Discord.

![image](https://user-images.githubusercontent.com/23151962/124032424-6a3ec400-d9ad-11eb-91bc-c00885465c19.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @949mac probably *git clone* is disabled in your code generation settings... please disable this option only if you want to generate the code files (models, controllers), not a complete project, as you can read in the tip on the right side of the option:

```
When disabling 'git clone' before the first code generation, Vemto will not generate a complete 
Laravel application, but only the code files (Controllers, Models, etc). Other commands like 
'composer install' or 'php artisan' will be ignored. Disabling it on already generated applications has 
no effect except a small performance improvement
```

![image](https://user-images.githubusercontent.com/11933789/124136424-25716680-da5b-11eb-8c4f-d6fd605968e4.png)
