### ISSUE TITLE
Error Master Detail

### ISSUE THREAD

**Issue by opizarrosilva** [TiagoSilvaPereira/vemto-issues#191]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
He creado un CRUD y agregue MASTER DETAIL, después generé el código y hasta ahí todo funcionó bien sin errores y sin advertencias. Al ingresar a la aplicación y probar el CRUD me salió un error: 
"Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'partida.nombre' in 'where clause' (SQL: select count(*) as aggregate from `partidas` where `partida`.`nombre` = Partida 1)"

**To Reproduce**
1. Cree el Schema e incluí las entidades.
2. Cree la relación Uno a Muchos entre "Iteme" y "Partida" 
3. Cree el CRUD a partir de "Iteme" e inclui un Master Detail con "Partida"
4. Generé el codigo.
5. Al ejecutar en el navegador un Insert salió el error.

**Screenshots**
![image](https://user-images.githubusercontent.com/83740682/125144271-5270e980-e0eb-11eb-9992-8dff7e787e82.png)
![image](https://user-images.githubusercontent.com/83740682/125144310-6ddbf480-e0eb-11eb-89e8-29d9c61c2e87.png)
![image](https://user-images.githubusercontent.com/83740682/125144331-83511e80-e0eb-11eb-9574-d08750c5e5af.png)
![image](https://user-images.githubusercontent.com/83740682/125144358-9c59cf80-e0eb-11eb-89fd-4142b87c6753.png)
![image](https://user-images.githubusercontent.com/83740682/125144414-d88d3000-e0eb-11eb-9f60-d8a9429f3630.png)
![image](https://user-images.githubusercontent.com/83740682/125144602-610bd080-e0ec-11eb-9395-5cb518fa7dcb.png)
![image](https://user-images.githubusercontent.com/83740682/125144652-83055300-e0ec-11eb-832c-585070065115.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Chrome: Versión 91.0.4472.124 (Build oficial) (64 bits)

**Comment by TiagoSilvaPereira** [comment]
Hi @opizarrosilva seems like you added the "Nombre" field after running the migrations. You need to run them again. You can do it by clicking on the **Run** button on Vemto, or you can execute it directly on the terminal:

```
php artisan migrate:fresh --seed
```

**Comment by opizarrosilva** [comment]
Hi Tiago, I think the error is in how the validation is written:
![image](https://user-images.githubusercontent.com/83740682/125148791-be128100-e102-11eb-858b-7f923d17a80b.png)

When it does the validation it tries to fetch the column "partida.nombre" and you should search for the column "partidas.nombre", this is not possible to correct by running "php artisan migrate:fresh --seed"
