### ISSUE TITLE
[BUG] When a relationship is deleted, MasterDetail views are not deleted

### ISSUE THREAD

**Issue by nocodelab** [TiagoSilvaPereira/vemto-issues#196]
Hello,
As mentioned in the title, when I delete a relationship the related MasterDetail views are not deleted accordingly.
This generate a crash during the code generation.
Manually removing the MasterDetail view(s) solves the issue.

Cheers!

**Comment by TiagoSilvaPereira** [comment]
Hi @nocodelab thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.10
