### ISSUE TITLE
[BUG] Factories are not updated when updating model fields

### ISSUE THREAD

**Issue by nocodelab** [TiagoSilvaPereira/vemto-issues#198]
Hello,
If i add/remove/edit a field, the model's factory is not updated accordingly.

Cheers!

**Comment by TiagoSilvaPereira** [comment]
Hi @nocodelab thank you for reporting... could you please share more details about this issue? I tried to reproduce it here, but it seemed to work

**Comment by TiagoSilvaPereira** [comment]
Closing for now... please feel free to reopen if the problem persists
