### ISSUE TITLE
[IMPROVEMENT] Skipped files section should be taller or resizable 

### ISSUE THREAD

**Issue by nocodelab** [TiagoSilvaPereira/vemto-issues#200]
Hello,
As per the screenshot attached I believe that the skipped files section should be resizable (or at least taller).

<img width="2032" alt="Screenshot_2021-07-07_at_15 37 50" src="https://user-images.githubusercontent.com/4540118/125503403-cee88c10-141d-494b-a211-dee08d9eee47.png">

The screenshot has been taken on a retina (resized @ 1080) monitor.

Cheers!

**Comment by TiagoSilvaPereira** [comment]
Hi @nocodelab thank you for your suggestion

**Comment by TiagoSilvaPereira** [comment]
@nocodelab fixed on 0.9.10
