### ISSUE TITLE
[BUG] Schema Editor relationship connectors disconnecting when entity is moved

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#201]
**Describe the bug**
In the schema editor the entity connector is rendering incorrectly but only on one entity.
Moving it to th right causes the entity to resize and for one relationship connector to draw as unconnected
Also right hand scroll bar is flashing

**To Reproduce**
1. Go to schema editor
2. Click on connected accounts entity
3. move entity to the right
4. See attached video

**Expected behavior**
entity should not resize and relationship connectors should render as connected to the entity

**Screenshots**
Attached a screen recording

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.4 (Mac Mini M1)
 - Browser Brave
 - Version Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (arm64)

https://user-images.githubusercontent.com/4245429/125789018-f62b9f8f-cee1-41b0-ae21-5ffa2d55934f.mov

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj thank you for reporting, I'll check what is happening

**Comment by deanlj** [comment]
great, thanks

forgot to say this is v0.9.9 with a new project

**Comment by TiagoSilvaPereira** [comment]
@deanlj fixed on 0.9.10
