### ISSUE TITLE
Urls not clickable links on Show pages

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#206]
Greetings,

I previously reported several issues relating to use of  Input Type of Url:   

https://github.com/TiagoSilvaPereira/vemto-issues/issues/189

That issue was closed.   However, it looks as though **Urls** are **still not clickable links on the Show page**.   I believe all the other related issues were fixed, including making Urls clickable on Index pages.

Expected behavior

I had expected that by using the Input Type of Url I would get clickable links on both the Index and Show pages.

Thanks for the awesome app!

**Comment by TiagoSilvaPereira** [comment]
Hi @relayer464 thank you for reporting, I wish to fix it on the next minor version

**Comment by TiagoSilvaPereira** [comment]
@relayer464 fixed on 0.9.10
