### ISSUE TITLE
[Bug] Migrations fail due to order of migration files

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#210]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
When I run the **php artisan migrate:fresh --seed** command I receive the following error:

General error: 

> 1215 Cannot add foreign key constraint

From what I can tell, the problem is that some of the **add_foreigns_to** migrations have a higher order number than the **create** migrations they're referring to.  In short, some of the the **add_foreigns_to** don't work because the tables they're supposed to be added to are not all created yet because the migration files are not ordered properly.

I can force the migrations through if I manually renumber the files so that all **create** migrations have lower numbers than the **add_foreigns_to** migration files.  For me, the easiest way to reorder them manually has been to just insert a "1" prior to the sequence number of  **add_foreigns_to** migration files (Example: 2021_02_24_0000**29**_add_foreigns_to_bookmarks_table becomes 2021_02_24_000**129**_add_foreigns_to_bookmarks_table).

I am not sure, but suspect they're getting out of order due to the fact that I am making changes to the Entities, since I didn't run into this problem the first time I generated the project and ran the migrations command.

I saw that the same or similar issue was reported and closed (link below), but I just wanted to let you know the same or similar problem appears to still exist.

https://github.com/TiagoSilvaPereira/vemto-issues/issues/30

**Expected behavior**
I was expecting that as I made tweaks to my Entities I could regenerate my project as needed without running into issues relating to the execution order of the migrations and having to manually reorder them.

Thanks!

**Comment by TiagoSilvaPereira** [comment]
Hi @relayer464 thank you for reporting, I'll fix it as soon as possible

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.9.11
