### ISSUE TITLE
[Bug] On Create and On Update option not working

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#211]
**Describe the bug**

I add several fields using the CRUD Editor that I only want to be seen on the On Show page, so I uncheck On Create, On Update, and On Index in the field Settings section.

![image](https://user-images.githubusercontent.com/20197966/128450014-2108ca38-22f3-4f95-81da-daac7899e45f.png)

After I regenerate the project the field is not longer viewable on the Index page (the expected behavior), but the form field is still on the newly generated Created and Update pages.  Example:

![image](https://user-images.githubusercontent.com/20197966/128450466-c2e90655-4637-4a16-9797-70fe6ad7fbfd.png)

**To Reproduce**
1. Go to CRUD Editor and uncheck On Create and/or On Update
2. Generate Code
3. View results in browser to confirm field is removed from designated views (in my case it was not)

Note: I cleared both browser and View cache but it didn't help.

**Expected behavior**
When you uncheck the On Create and On Update for field's settings, that field would not be visible on those pages

Thanks!

**Comment by TiagoSilvaPereira** [comment]
@relayer464 thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.0.1
