### ISSUE TITLE
[BUG] Command failed: npm -v /bin/sh: npm: command not found

### ISSUE THREAD

**Issue by gpx75** [TiagoSilvaPereira/vemto-issues#22]
**Describe the bug**

Hi by executing a run i got the error /bin/sh: npm command not found 
npm and node is installed via nvm with latest version, I tried  to install with brew as well but get the same error.

npm path is set to /Users/gp/.nvm/versions/node/v15.0.1/bin in the application or left blank

❯ which npm
/Users/gi/.nvm/versions/node/v15.0.1/bin/npm

❯ npm -v
7.0.3

❯ node -v
v15.0.1

Thanks in advance
GP

**Comment by taliesinpenbardd** [comment]
Same on MacOS 10.15.7, with NPM installed via Homebrew and added to the PATH:
```
$ which npm
/usr/local/bin/npm
```

```
$ npm -v
7.0.3
```

But Vemto cannot find NPM, either if I let it use the global NPM or if I fill in `/usr/local/bin` in the general parameters. Can't go further yet, the app won't run.

`Error: Command failed: /usr/local/bin/npm -v env: node: No such file or directory`
but in my terminal, `$ /usr/local/bin/npm -v` works fine and gives me the NPM version (7.0.3).

**Comment by TiagoSilvaPereira** [comment]
Hi @gpx75 @taliesinpenbardd I just launched Vemto 0.5.5 that fixes these issues. If you have another problem, feel free to open an issue here. Thank you and have a nice day

**Comment by gpx75** [comment]
Hi @TiagoSilvaPereira  

Same issue after upgrading 

MAC version 10.15.7


![image](https://user-images.githubusercontent.com/10692912/97970325-a6d80280-1dc1-11eb-95a7-542e83cf7384.png)


this is from the terminal notice the last command throwing a syntax error by prefixing /bin/sh:

![image](https://user-images.githubusercontent.com/10692912/97971329-24504280-1dc3-11eb-8362-bb31e050b41b.png)

thanks & have a good day
