### ISSUE TITLE
Improvements on the "Add CRUD" modal

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-issues#220]
This image shows all the entities that I can add a CRUD to, but note that the list is sorted in an "unknown" way and you can only search by the first letter of the name.

![image](https://user-images.githubusercontent.com/17914565/130361933-820e6041-3a0f-441a-876e-164b3e127c91.png)

The suggestions are:

1. Sort the options A-Z
2. Change the component from "SELECT" to "SELECT with Search" similar to [Select2](https://select2.org/getting-started/basic-usage)
3. Highlight with Bold the Entities that do not yet have CRUD.
4. Mark with * and Bold the Entities that were added since the last time this modal was opened.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.0.1
