### ISSUE TITLE
Missing "new_title" field in "Settings" tab of "CRUD" screen

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-issues#222]
"Settings" tab fields:

![image](https://user-images.githubusercontent.com/17914565/130463163-4fb61aa1-f627-4a76-bc93-129a9e84bbab.png)

Currently generated fields, I took an example from the file in `resources/lang/crud.php`

![image](https://user-images.githubusercontent.com/17914565/130463415-b0852e19-471f-480b-ac2c-84d51d3faac4.png)

According to the menus:

Index Page Title     -> `index_title`
Create Page Title   -> `create_title`
????                       -> `new_title`
Edit Page Title        -> `edit_title`
Show Page Title     -> `show_title`

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.0.1
