### ISSUE TITLE
Option for change text placeholder on select element

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-issues#223]
The text "Please select the" on placeholder this image:
![image](https://user-images.githubusercontent.com/17914565/130471926-62963610-ddb5-486e-a11e-02faec175622.png)

This text not found option for change in `resource/lang/crud.php`
![image](https://user-images.githubusercontent.com/17914565/130471977-40378ded-ab58-4e49-ac2d-cab1adce341d.png)

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.0.1
