### ISSUE TITLE
[BUG] Order of blank fields in Schema editor

### ISSUE THREAD

**Issue by taliesinpenbardd** [TiagoSilvaPereira/vemto-issues#23]
When adding fields to an Entity in the Schema editor, after a few fields added, the new blank fields appear inside the list, instead of at the end of it. It can be confusing to look for it, when it'd be easier to know that it's the last field.

Plus reordering the fields, for the sake of lisibility, is confusing : all of them move when one is moved. I guess it would be more logical to just have the one selected to move.

OS: MacOS 10.15.7
Vemto 0.5.4

Keeping on testing :)

**Comment by TiagoSilvaPereira** [comment]
Hi @taliesinpenbardd thank you for reporting this issue... I'll give an eye on it. Cheers

**Comment by TiagoSilvaPereira** [comment]
Hi @taliesinpenbardd I just fixed it on Vemto 0.5.5... Have a nice day, thank you

**Comment by taliesinpenbardd** [comment]
That's corrected, thank you!
