### ISSUE TITLE
Another NPM / NVM issue (macOS 11.5.2)

### ISSUE THREAD

**Issue by lhilton** [TiagoSilvaPereira/vemto-issues#233]
**Describe the bug**
I cannot generate code on a clean install of vemto 0.9.10, in a newly created (but not empty, it has a couple of models/apps) project. Error is `no such file or directory`.

**To Reproduce**
1. Use macOS 11.5.2
2. Use NVM to manage node versions
3. Run in terminal `nvm use 14.17.6`
4. Set vemto global path for NPM to: `/Users/{{ your profile name }}/.config/nvm/14.17.6/bin`
5. Attempt to generate code

**Screenshots**
<img width="971" alt="Screen-Shot-2021-09-09-12-36-11 28" src="https://user-images.githubusercontent.com/745338/132752827-c9826f47-8cff-4e96-85a8-78825ee24d30.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser n/a
 - Version 0.9.10

**Comment by TiagoSilvaPereira** [comment]
Hi @lhilton could you please test if it happens when creating a new project?

**Comment by lhilton** [comment]
@TiagoSilvaPereira identical results.

The issue appears to be the way that NPM is being called by Vemto. When installed via [NVM](https://github.com/nvm-sh/nvm), the npm file in the path is a node.js app, not a SH script. When your call is issued, the SH engine encounters JS and dies.

I tried changing the symlink that NVM uses, however this broke everything else in that ecosystem so I never tested Vemto in that configuration.

**Comment by lhilton** [comment]
@TiagoSilvaPereira is there a way to disable the command to check? For my immediate needs, I can do without the frontend asset builds, I can always handle that myself.

**Comment by TiagoSilvaPereira** [comment]
Hi @lhilton currently there is no way to disable the "check process"... could you please try installing NPM in another way? I'll add a way to disable the "check process" on future versions, and I'll investigate how to bypass this limitation from NVM

**Comment by TiagoSilvaPereira** [comment]
Hi @lhilton I just added a way to disable the "check dependencies" process. Please update to 0.9.11
