### ISSUE TITLE
Improvement: unique field unique faker attribute

### ISSUE THREAD

**Issue by thijmenogerion** [TiagoSilvaPereira/vemto-issues#237]
When creating a unique database field. please use the faker->unique->name (for example)

**Comment by carloshagge2** [comment]
Faker\Generator::getFormatter("cpf") erro ao gerar campo cpf no banco de dados via migration
alguém aí sabe como fazer essa faker?

**Comment by TiagoSilvaPereira** [comment]
@thijmenogerion thank you for your suggestion

**Comment by TiagoSilvaPereira** [comment]
@carloshagge2 you can use the CPF formatter directly and combine it with the unique rule if necessary: https://fakerphp.github.io/locales/pt_BR/#fakerproviderpt_brperson

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.0.1
