### ISSUE TITLE
Multiple Belongs To same table causes conflicting relation method

### ISSUE THREAD

**Issue by luttje** [TiagoSilvaPereira/vemto-issues#244]
Awesome project, loving it! This bug is minor and can be fixed manually quickly, though would be nice to have generated code work without errors like this.

**Describe the bug**
If I have a single model (e.g: Log) which belongs to another model twice (e.g: Player, one player is specified in actor_id, the other in subject_id) the resulting Player model will get 2 relationship methods with the same name (logs)

This causes an exception when trying the website immediately after generating:
```
Symfony\Component\ErrorHandler\Error\FatalError
Cannot redeclare App\Models\Player::logs() 
```

**To Reproduce**
Create two models:
* Log
* Player

Ensure the Log model has two belongs to relations to Player:
* actor_id
* subject_id

![image](https://user-images.githubusercontent.com/2738114/136198404-c8031e0c-93bf-4279-b640-9fd8fb866345.png)
![image](https://user-images.githubusercontent.com/2738114/136198619-9c251c56-711f-4515-a380-fb04ebac0839.png)

**Expected behavior**
Asking for Vemto to understand my intentions is impossible, though if it detects an existing method in the model it could append a number. E.g: logs2() so no errors is thrown on testing.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.9.11

**Comment by TiagoSilvaPereira** [comment]
Hi @luttje thank you for your suggestion. 

For now, what you can do is to change the names of the inverse relationships on the Schema Editor (when you create the belongsTo relationship, it generates an inverse relationship on the inverse model. Just changing the name of this inverse relationship will work too).

**Comment by luttje** [comment]
That makes sense.

Perhaps a 'conflict indicator' (❗) on the ERD could direct users to perform that action if Vemto detects this problem.

Anyway thanks for the instruction.

**Comment by TiagoSilvaPereira** [comment]
> That makes sense.
> 
> Perhaps a 'conflict indicator' (exclamation) on the ERD could direct users to perform that action if Vemto detects this problem.
> 
> Anyway thanks for the instruction.

Good suggestion, I'll add something similar to that on future versions

**Comment by TiagoSilvaPereira** [comment]
@luttje added this feature to Vemto 1.1.0

**Comment by fredyns** [comment]
instead of using number as suffix, i suggest using related column as suffix.
eg: logsAsActor() and logsAsSubject() 
taht is self explained

> **Expected behavior** Asking for Vemto to understand my intentions is impossible, though if it detects an existing method in the model it could append a number. E.g: logs2() so no errors is thrown on testing.
>
