### ISSUE TITLE
Import ? 

### ISSUE THREAD

**Issue by ahpetrot** [TiagoSilvaPereira/vemto-issues#246]
I can't seem to find anything in the documentation on how import is supposed to work ?  

I had to do system rebuild after a very bad crash and while I have my crud generated files I don't have the original vemto/storage. 

Wondering if I can import the source..

**Comment by TiagoSilvaPereira** [comment]
Hi @ahpetrot to import a project, you need first to export it. If you have the vemto/storage folder, just copy it to the new installation folder and it will work: https://vemto.app/docs/1.x/backup
