### ISSUE TITLE
vemto doesnot support multi window 

### ISSUE THREAD

**Issue by AlanKurdish** [TiagoSilvaPereira/vemto-issues#248]
when opening 2 windows of vemto second window asks for new active code..
it should support multi window...
Thanks.

**Comment by TiagoSilvaPereira** [comment]
@AlanKurdish thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
@AlanKurdish I'm closing, for now, as this behavior happens due to some Electron.js limitations. I'll add it to my backlog and return to it once I find a solution
