### ISSUE TITLE
[BUG] TypeError: Cannot read property 'save' of null

### ISSUE THREAD

**Issue by BriscoPeas93** [TiagoSilvaPereira/vemto-issues#25]
```
TypeError: Cannot read property 'save' of null
    at a.create (app://./js/project_crud.5b8caf35.js:1:26229)
    at app://./js/project_crud.5b8caf35.js:1:26067
```

---

vemto 0.5.4
Electron 8.5.2
darwin 19.6.0
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @BriscoPeas93 could you please provide a screenshot or more details showing when the error happens?

**Comment by TiagoSilvaPereira** [comment]
Hi @BriscoPeas93 could you please provide some screenshots so I can reproduce the issue? Thank you

**Comment by TiagoSilvaPereira** [comment]
Hi @BriscoPeas93 I'm closing for now... if the error continues, please feel free to comment here. Thanks
