### ISSUE TITLE
Enum datatype issues

### ISSUE THREAD

**Issue by ramakrishnamie** [TiagoSilvaPereira/vemto-issues#253]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.
PHP - Parse error, unexpected T_STRING, expecting ',' or ';' 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of details
