### ISSUE TITLE
Integrate with supabase

### ISSUE THREAD

**Issue by ibuilder** [TiagoSilvaPereira/vemto-issues#256]
Any thoughts on added support for supabase? https://supabase.io/

**Comment by TiagoSilvaPereira** [comment]
Hi @ibuilder this is the first time I hear about Supabase... it seems like an awesome platform, but with different technologies, so I think there is no easy way to integrate it with Vemto. Maybe someone could try creating a Vemto plugin, but I don't have any idea if that is possible.

Best regards,
Tiago

**Comment by ibuilder** [comment]
I'll work on it!  Good idea.
