### ISSUE TITLE
Not possible to generate on windows (composer not found in path) + solution

### ISSUE THREAD

**Issue by Patrikgrinsvall** [TiagoSilvaPereira/vemto-issues#257]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
Using windows 10 and composer 2.1. 
On windows, composer executable isn't called `composer` but `composer.bat` or `composer.phar`.  This works from terminal since extension is excluded. But not when using absolute path to the executable (might also be quotation marks)

For some reason, (i'm sure its in my path since it works in all tested terminals, screenshot attached) composer isn't found by vemto in path. 
Trying and set the path in the environment settings on homescreen. Problem is then, you can only specify folder name and not executable name, so result is:` Command failed: "c:\ProgramData\ComposerSetup\bin\composer" --version '"c:\ProgramData\ComposerSetup\bin\composer"' is not recognized as an internal or external command, operable program or batch file.`. 
When changing to composer.bat/phar, result is, `Command failed: "c:\ProgramData\ComposerSetup\bin\composer.bat\composer" --version '"c:\ProgramData\ComposerSetup\bin\composer.bat\composer"' is not recognized as an internal or external command, operable program or batch file.`. (It looks like i have setup with backslashes, but they are translated it seems, paths are added with forward slashes in vemto.).

*Solution*: When checking for environment executables, make a check if path is a directory or a file. If its a file, try and execute it. If a directory, execute composer like today. Alternativley, use a file browser dialog where user point to the exact executable. 
The same applies for php and likley npm and git as well.

This will also bring the feature run different versions of the environment deps when generating code.

**To Reproduce**

*See above*

**Expected behavior**
I would expect it to be possible to generate the application, as of now its useless...

**Screenshots**

https://easycaptures.com/fs/uploaded/1631/7281610699.png

**Desktop (please complete the following information):**
 - *Windows 10*
 - *not applicable*
- *it says 1.0.0 but its latest from website*

**Additional context**

**Comment by TiagoSilvaPereira** [comment]
Hi @Patrikgrinsvall could you please send a screenshot of your Vemto Settings screen? I tried it here with the same settings and it worked well:

![image](https://user-images.githubusercontent.com/11933789/143888355-ee93ad13-c0fb-4f14-84ec-8ef36d2ffe26.png)

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of response... please feel free to open it again if necessary

**Comment by Patrikgrinsvall** [comment]
Sorry for late response. It seems to be related to me having a very customized terminal setup. 

The workaround for that scenario is to  not generating anything related to composer, npm etc. and also to not check option, "check dependencies"
