### ISSUE TITLE
Vemto v 1.0.2 : nullable button not working on this version

### ISSUE THREAD

**Issue by Loukili-Rachid** [TiagoSilvaPereira/vemto-issues#263]
![2021-12-17_163317](https://user-images.githubusercontent.com/11983029/146569042-6ea57974-9859-459d-92d1-81e20a9e779f.png)

**Comment by TiagoSilvaPereira** [comment]
@Loukili-Rachid thank you for reporting. 

I tried to reproduce it, but without success.

Could you please share more details like your OS, and make a small screen capture of your whole screen showing the problem?

**Comment by TiagoSilvaPereira** [comment]
@Loukili-Rachid fixed on 1.0.3
