### ISSUE TITLE
Spatie\Permission\Exceptions\PermissionDoesNotExist

### ISSUE THREAD

**Issue by jsthind** [TiagoSilvaPereira/vemto-issues#264]
Getting a "PermissionDoesNotExist" error when I log in to Dashboard. Fresh installation with a single CRUD. 

![error](https://user-images.githubusercontent.com/456605/146958298-2bbdd0ef-4ac3-4ebc-979b-9794d82c3681.png)

The project file is at https://stagingbox.dev/ecom.vemto

**Comment by TiagoSilvaPereira** [comment]
Hi @jsthind did you run the seeders?

**Comment by jsthind** [comment]
No, I didn't generate or run the seeders. 

Is it possible to skip seeders for some models? Or do I need to go in and manually edit files?

**Comment by TiagoSilvaPereira** [comment]
Hi @jsthind so probably that is the problem, as the permissions are created by a seeder called PermissionsSeeder. It is not possible to disable a specific seeder from Vemto, you would need to manually edit the code to do it, rr you can just run the specific seeder you want from your terminal
