### ISSUE TITLE
Class "App\Filament\Resources\Number" not found

### ISSUE THREAD

**Issue by zerocooldeveloper** [TiagoSilvaPereira/vemto-issues#267]
![image](https://user-images.githubusercontent.com/17159290/151033058-3d9469c6-6b98-47aa-b048-b9e2f3a6ecff.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @zerocooldeveloper , sorry for this problem... please change Number to TextInput and add the ->number() modifier to the field. We'll update the Filament plugin soon to fix this problem

**Comment by zerocooldeveloper** [comment]
Thanks
