### ISSUE TITLE
Edit Password User Cant Working

### ISSUE THREAD

**Issue by shofeather** [TiagoSilvaPereira/vemto-issues#271]
halo, i have problem, when edit user then notif succesfully.
but, I try to login. the password still with old password.
btw I already update vemto in version 1.0.5

please help, thanks

![1](https://user-images.githubusercontent.com/76820197/151269381-7d0dffb0-eda9-4fe5-9c3a-95479425404e.png)

![2](https://user-images.githubusercontent.com/76820197/151269403-22c64939-93ad-43a4-a5fc-296fd5b4b56b.png)

![3](https://user-images.githubusercontent.com/76820197/151269411-76cda01c-46a7-4112-8b26-723ea899816b.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @shofeather I'll fix this bug soon... for now, you can just add the **string** update validation on the password input and it will work well:

![image](https://user-images.githubusercontent.com/11933789/151372940-47b88459-e4c7-49bc-a47c-1032c117fe83.png)

**Comment by TiagoSilvaPereira** [comment]
@shofeather please use **nullable** instead of **string**

**Comment by TiagoSilvaPereira** [comment]
@shofeather fixed on Vemto 1.1.0
