### ISSUE TITLE
"The GET method is not supported for this route. Supported methods: POST." Is face this error in [ livewire master details ] 

### ISSUE THREAD

**Issue by Loukili-Rachid** [TiagoSilvaPereira/vemto-issues#272]
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.
http://localhost:8000/livewire/message/channel-category-channels-detail?page=2

**To Reproduce**
1. Go to 'master details (livewire)'
2.  edit some record then save 
3.  next try to go next page 2 
4. See error above : The GET method is not supported for this route. Supported methods: POST.

   
![2022-02-04_100546](https://user-images.githubusercontent.com/11983029/152502851-a29def02-9441-4a5b-80f1-4adbed211390.png)

As i see the pagination is changed from :

`<a href="http://localhost:8000/channel-categories/10/edit?page=2" > 2 </a>`
To :
`<a href="http://localhost:8000/livewire/message/channel-category-channels-detail?page=2">  2 </a>`

Environment : 
Vemto 1.0.5
Chrome latest
Windows 11

**Comment by Loukili-Rachid** [comment]
after i few searcher i found that we should use a trait
fix it with adding "use WithPagination;"  in livewire class component

like this example

class MusiqueCategorySingersDetail extends Component
{
use WithPagination;

**Comment by Loukili-Rachid** [comment]
@TiagoSilvaPereira Hi bro, could you please add this trait to default Vemto HasManyDetailLivewireComponent ?
 
use WithPagination;

**Comment by TiagoSilvaPereira** [comment]
Hi @Loukili-Rachid thank you for reporting... I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
@Loukili-Rachid fixed on Vemto 1.1.0
