### ISSUE TITLE
Plugin Issues 

### ISSUE THREAD

**Issue by silicahd** [TiagoSilvaPereira/vemto-issues#273]
I think this might be a bug. I am using the Filament plugin. I created some cruds and generated the dashboard. All is well. But if i add more tables and cruds it will generate with no issues. However when you go to see the dashboard. Only the default dashboard has the new cruds but the filament does not. If i uninstalled filament and reinstalled and generate again, all the cruds now show up on the filament dashboard.

The way i found about this. I created a table "Form" when trying to generate filament it will error out. Than if i rename to "Checklist" the error will persist. If i uninstall the plugin and reinstall and regenerate it will now work.

**Comment by TiagoSilvaPereira** [comment]
Hi @silicahd it is not a bug, you just need to check the created CRUD in the plugin settings to generate them. Please check the plugin Readme for more details.
