### ISSUE TITLE
Picture input field doesn't work with Admin LTE on a master-detail form (on the detail side of things)

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#276]
**To Reproduce**
1. Create a master-detail form, the detail form needs to include a picture field
2. Enable the Admin LTE plugin
3. Generate the code
4. Open the site and try to add data using the master-detail form, on page load this error shows up in the console:

`Uncaught ReferenceError: imageViewer is not defined
    at eval (eval at d.el (alpine.js:144:14), <anonymous>:3:36)
    at d.el (alpine.js:144:14)
    at d (alpine.js:131:21)
    at f (alpine.js:139:12)
    at new be (alpine.js:1461:89)
    at alpine.js:1614:42
    at alpine.js:1596:26
    at l (alpine.js:90:9)
    at l (alpine.js:94:7)
    at l (alpine.js:94:7)`

5. Clicking on "New" button doesn't trigger any modal with detail form

**Expected behavior**
Clicking on "New" will show a modal with the detail form, including any picture fields (this works if the Admin LTE plugin is disabled)

**Screenshots**
![image](https://user-images.githubusercontent.com/2504486/156219688-fd71f216-803f-4897-b809-235a29767312.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad thank you for reporting, I'll check it asap

**Comment by henriquek3** [comment]
Hello, I went through the same problem and fixed it by adjusting the alpinejs version, the version used with the AdminLTE theme was version 2 so I used version 3 which is compiled without the theme plugin.

![Captura de Tela-20220314-153342-807x156](https://user-images.githubusercontent.com/17914565/158247742-6aa6dc7c-bf3c-4dda-a1ef-0a25fd1ff4c2.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @henriquek3 thank you, we'll fix the plugin soon

**Comment by henriquek3** [comment]
@TiagoSilvaPereira boa tarde, na versão 1.1.4 ainda esta com o mesmo problema. A versão do plugin do AdminLTE ainda esta na versão 1.0.

**Comment by TiagoSilvaPereira** [comment]
@henriquek3 not fixed yet

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.5
