### ISSUE TITLE
Validation rule for a Picture field changes from "image" to "string" after changing nullable/not nullable

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#277]
**Describe the bug**
The validation rule for a Picture field changes from "image" to "string" after changing the settings on the database, changing from nullable to not nullable.  Changing a field from "nullable" to "not nullable" in the db shouldn't change the expected input type from "image" to "string" in the validation rules.

**To Reproduce**
1. Create a field, type String, not nullable
2. Add a Picture field on a CRUD form, connected to the field in db
3. Notice the validation rule is set to type "image", not string (correct)
4. Edit the field on the db, set it to "nullable"
5. Edit the CRUD form, notice the validation rules changed from "image" to "string" (wrong)

**Expected behavior**
Changing a field in the db from "nullable" to not nullable, should only add "required" to the validation rule, or vice versa remove "required" if a field in the db is changed from not nullable to "nullable".

**Screenshots**
Loom: https://www.loom.com/share/181fc4330d814bf3a801b1fa81e25304

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by TiagoSilvaPereira** [comment]
@manfredekblad thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.5
