### ISSUE TITLE
Can't generate the code using TailwindCSS/Jetstream: error messages and code generation aborted

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#278]
**Describe the bug**
Can't generate the code using TailwindCSS/Jetstream, but Bootstrap/Laravel UI works fine. Error messages during the Generate-step from composer during the code generation when its set to TailwindCSS/Jetstream

**To Reproduce**
1. In the Settings->Views, set it to use TailwindCSS/Jetstream
2. Generate code
3. Error messages appear and the code generation is aborted

**Expected behavior**
Code generated successfully with any of the options set under Settings->Views.

**Screenshots**
Loom: https://www.loom.com/share/96368c3a30ca45da824c6c2614c7adb4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by TiagoSilvaPereira** [comment]
@manfredekblad it is not a bug... when you change a project from Bootstrap to Jetstream, there are a lot of changes to the project structure. So the recommended is to delete the previously generated code and generate it again if you are changing the project UI template.
