### ISSUE TITLE
Validation rule is set to "string" as default on File input field (should be "file")

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#279]
**Describe the bug**
Validation rule is set to "string" as default on File field (should be "file"). On Picture fields, its correctly set as "image", not string. But on File fields, its set to "string" as default which the user need to change manually for the CRUD to work. If the user doesn't change it manually from "string" to "file" (or simply remove "string"), then the CRUD-user will see a validation message that the field "... must be a string.

**To Reproduce**
1. Add a File input field to a CRUD form
2. Look at the validation rules, it will expect a "string"
3. Generate the code
4. Open the CRUD and try to upload a file, then Save
5. The validation message shows "... must be a string."

**Expected behavior**
The default type in the validation for a File field should be "file", not "string".

**Screenshots**
![image](https://user-images.githubusercontent.com/2504486/156620162-e3b18f8b-1533-4310-813b-8477fc8d393b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by TiagoSilvaPereira** [comment]
@manfredekblad thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.3
