### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by gpx75** [TiagoSilvaPereira/vemto-issues#28]
Hi @TiagoSilvaPereira  

Same issue after upgrading 

MAC version 10.15.7

![image](https://user-images.githubusercontent.com/10692912/97970325-a6d80280-1dc1-11eb-95a7-542e83cf7384.png)

this is from the terminal notice the last command throwing a syntax error by prefixing /bin/sh:

![image](https://user-images.githubusercontent.com/10692912/97971329-24504280-1dc3-11eb-8362-bb31e050b41b.png)

thanks & have a good day

_Originally posted by @gpx75 in https://github.com/TiagoSilvaPereira/vemto-issues/issues/22#issuecomment-721016041_

**Comment by TiagoSilvaPereira** [comment]
Hi @gpx75 thank you for reporting... what happens if you add the npm path to the Vemto settings on Home Page?

**Comment by buckhornmktg** [comment]
Same problem here... even with the correct path in the Vemto settings.

**Comment by TiagoSilvaPereira** [comment]
@gpx75 @buckhornmktg I think I discovered what is happening... I'll launch a fix in some hours. Sorry for the inconvenience.

**Comment by buckhornmktg** [comment]
@TiagoSilvaPereira fantastic! Thank you.

**Comment by TiagoSilvaPereira** [comment]
@gpx75 @buckhornmktg please try with **Vemto 0.5.7**... I hope it works now, I made several changes to improve macOS generation. Have a nice day

**Comment by buckhornmktg** [comment]
Yes, works now. Thanks. I removed the settings from the home screen and no errors, seems like the correct $PATH var is being used now.

**Comment by TiagoSilvaPereira** [comment]
Perfect @buckhornmktg :clap: :clap: :clap: closing for now... some problem, please feel free to comment here
