### ISSUE TITLE
Login & Registration forms are not visible after generating code and running the app

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#280]
**Describe the bug**
The login and registration forms are missing after generating the code successfully and running the application.

**To Reproduce**
1. Generate the code
2. Run the application
3. View the application in the browser
4. Click to Login form
5. No login form is visible
6. Click to Register form
7. No register form is visible

**Expected behavior**
Login form and Registration form visible and functional.

**Screenshots**
https://www.loom.com/share/d9dd471989014003a086559405d1dd6b

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad could you please try deleting the generated code and generating it again?

**Comment by TiagoSilvaPereira** [comment]
Vemto doesn't touch the login/registration files, so it probably was due to some issue with laravel/ui
