### ISSUE TITLE
Form field settings (On Index) are changed when a field in the table structure changes nullable/not nullable

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#282]
**Describe the bug**
The form field settings change their value when the same field changes the nullable/not nullable state. This means, making changes to the database affects the way the CRUD is rendered even for unrelated settings. So this means the same work has do be done multiple times.

Changing the nullable/not nullable setting on a db field shouldn't impact the settings on the CRUD for OnCreate/OnUpdate/OnShow/OnIndex.

**To Reproduce**
1. Uncheck a form fields "On Index" (state = unchecked)
2. Change the field in the db, nullable/not nullable
3. Go back to the form editor, the "On Index" is back to checked state

**Expected behavior**
The OnIndex keeps it settings regardless if user change a db fields nullable/not nullable state

**Screenshots**
https://www.loom.com/share/fcf85818689847d1aca05b4340d61947

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.5
