### ISSUE TITLE
Problem with Filament plugin

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [TiagoSilvaPereira/vemto-issues#283]
Error when calling **getCorrectInputFromFieldAndCrud()**:

![1](https://user-images.githubusercontent.com/11933789/157888827-5f3debd8-2080-4e1b-8def-236ef2bff1fd.png)

**Comment by TiagoSilvaPereira** [comment]
tagging @nicollassilva

**Comment by silicahd** [comment]
I wanted to add more info on this. The project was created using Vemto 1.0.5 and Filament 1.0.1. 
I updated to 1.1.2 and Filament 1.0.2 and this error comes up as a reuslt the project looks empty. 
![image](https://user-images.githubusercontent.com/7761519/159148084-72decefc-5d84-4bc3-9dd7-24d176bc655b.png)

However I can generate the project if I diable Filament.

**Comment by silicahd** [comment]
I had to delelte all the CRUD views and create new one.

**Comment by silicahd** [comment]
I created a new project and I am having the same error. This is a bug in Vemto 1.1.2 

You cant create cruds with Foreign Key

![image](https://user-images.githubusercontent.com/7761519/159178367-5222c9f1-3976-47e9-9810-188ccd375cf5.png)
![image](https://user-images.githubusercontent.com/7761519/159178406-bbd1298d-e77f-4719-bd3f-59e354571a0d.png)

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.5
