### ISSUE TITLE
Error creating new project and adding URL from empty Repository 

### ISSUE THREAD

**Issue by gerzahim** [TiagoSilvaPereira/vemto-issues#284]
**Describe the bug**
If you create a new project and add the URL from an empty Repository
and that Repository was just created and empty or maybe only contains the README file. 

Vemto will generate the files project and will try `composer install` but the composer.json file does not exist 
same for package.json 

At the end a Project will be created without composer libraries. 

Will be nice to add a disclaimer saying if add Repository link must contain composer.json file and package.json
or add validation on vemto to detect composer.json file
 if not exist add Laravel composer file. 

![2022-03-11_18-41-53](https://user-images.githubusercontent.com/11461029/157993643-61c2cbfb-76b5-4589-a142-fb47baf2ac4f.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @gerzahim I'm closing for now, as it is not really a bug... as you can see in the feature description below, Vemto will use a Laravel repository to start the application, so you always need to use a repository containing a Laravel application base.

![image](https://user-images.githubusercontent.com/11933789/159294879-77af333d-297d-44d0-baf8-0216b91b3c02.png)
