### ISSUE TITLE
issue not creating .env file and jetstream also not installed by vemto application

### ISSUE THREAD

**Issue by mukuldevd2** [TiagoSilvaPereira/vemto-issues#285]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mukuldevd2** [comment]
no I already do these things but .env file is look blank

**Comment by TiagoSilvaPereira** [comment]
@mukuldevd2 could you please try with a new project?

**Comment by mukuldevd2** [comment]
ok I will try and revert you
