### ISSUE TITLE
Can't resolve 'popper.js' and bootstrap.js 

### ISSUE THREAD

**Issue by abkrim** [TiagoSilvaPereira/vemto-issues#286]
When re-run **Generate Code** get this error 

```
WARNING in ./resources/js/bootstrap.js 9:18-49
Module not found: Error: Can't resolve 'popper.js' in '/home/abkrim/Sites/sitelight/resources/js'

WARNING in ./resources/js/bootstrap.js 10:29-46
Module not found: Error: Can't resolve 'jquery' in '/home/abkrim/Sites/sitelight/resources/js'
````

## Setup of app

Plugins: Fillament
Views
- TailwidnCSS
- Laravel UI (Breeze broken more complicated)
- Theme default
- Hotwire disabled

**To Reproduce**
1. Click Generate code
2. Cheks all except Force ovewrite files 
3. Generate check depenedencies. npm install, npm run dev 

**Expected behavior**
I like full deploy without error on npm with errors

```
✔ Compiled Successfully in 1181ms
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┐
│                                                                                                                                                                           File │ Size     │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┤
│                                                                                                                                                                     /js/app.js │ 1.57 MiB │
│                                                                                                                                                                    css/app.css │ 27.5 KiB │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┘
WARNING in ./resources/js/bootstrap.js 9:18-49
Module not found: Error: Can't resolve 'popper.js' in '/home/abkrim/Sites/sitelight/resources/js'

WARNING in ./resources/js/bootstrap.js 10:29-46
Module not found: Error: Can't resolve 'jquery' in '/home/abkrim/Sites/sitelight/resources/js'

webpack compiled with 2 warnings
```
![Castris_20220317_211606](https://user-images.githubusercontent.com/1238625/158888021-4fc3cfe9-3b74-454c-a61a-d50d1f9399d5.jpg)

**Desktop (please complete the following information):**
 - Linux Ubunut 20.04
 - Browser Not applicable

## Edited
I delete the project folder and start from 0.

Change from UI Template to Laravel UI, but no changes.

To avoid the error of jquery and pooper (what jquery is used at this point I do not understand) and run again and nothing does not work menus.
![Castris_20220318_062910](https://user-images.githubusercontent.com/1238625/158943343-4f74e3b9-7cd7-4eb8-98eb-c6ff9a22127c.jpg)

## Video
https://diwan.tamainut.net/index.php/s/DBwHEp8ce7gnpQA

**Comment by TiagoSilvaPereira** [comment]
@abkrim could you check if these dependencies are in the package.json?

**Comment by abkrim** [comment]
Hi.

New project from scrach. I've got the same problem.

On package.json not references to popper.js or jqery, but bootstrap require

I need add manually.

## Error
```
WARNING in ./resources/js/bootstrap.js 9:18-49
Module not found: Error: Can't resolve 'popper.js' in '/home/abkrim/Sites/api/resources/js'

WARNING in ./resources/js/bootstrap.js 10:29-46
Module not found: Error: Can't resolve 'jquery' in '/home/abkrim/Sites/api/resources/js'
```

## bootstap.js
```js
try {
    window.Popper = require('popper.js').default;
    window.$ = window.jQuery = require('jquery');
} catch (e) {}
```

## Other problema

> You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

## Notes

Why use jquery?
