### ISSUE TITLE
[BUG] No lock file found. Updating dependencies instead of installing from lock file

### ISSUE THREAD

**Issue by ShadowDark93** [TiagoSilvaPereira/vemto-issues#29]
Unhandled Promise Rejection
Error: Command failed: "C:/composer/composer" install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - laravel/ui[v3.0.0, ..., 3.x-dev] require illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[dev-master]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - laravel/framework 9.x-dev is an alias of laravel/framework dev-master and thus requires it to be installed too.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[9.x-dev (alias of dev-master)].
    - Root composer.json requires laravel/ui ^3.0 -> satisfiable by laravel/ui[v3.0.0, v3.1.0, 3.x-dev].
    at electron/js2c/asar.js:727:23
    at o.executeCommand (app://./js/chunk-common.8e4b1fa6.js:1:24805)
    at Le.runComposer (app://./js/generator.3d65f79b.js:1:28613)
    at app://./js/generator.3d65f79b.js:1:28364
    at new Promise (<anonymous>)
    at Le.runCommands (app://./js/generator.3d65f79b.js:1:28335)
    at Le.start (app://./js/generator.3d65f79b.js:1:28300)
    at gt.callProjectGenerators (app://./js/generator.3d65f79b.js:1:34553)

**Comment by TiagoSilvaPereira** [comment]
Hi @ShadowDark93 please upgrade to **Vemto 0.5.7**. This problem was happening because today, the Laravel team changed the master branch to the upcoming Laravel 9, so Vemto was installing the wrong version. I just fixed it to install Laravel 8 correctly. Cheers

**Comment by ShadowDark93** [comment]
solved with it, is so cool this app, I love it.... <3
