### ISSUE TITLE
unhandled promise rejection. timeout exceeded

### ISSUE THREAD

**Issue by d4rkr3pt0r** [TiagoSilvaPereira/vemto-issues#290]
```
Error: timeout exceeded
    at e.exports (app://./js/chunk-vendors.e7701b3f.js:80:13889)
    at XMLHttpRequest.y.ontimeout (app://./js/chunk-vendors.e7701b3f.js:645:2784)
```

---

vemto 1.1.2
Electron 8.5.5
win32 10.0.19044
Locale: en-US

**Comment by d4rkr3pt0r** [comment]
@TiagoSilvaPereira Actually it happens in random delays. Even when I don't work with the application and it's minimized in the taskbar. Sometimes the error shows multiple times per minute. I don't know what's the problem.

**Comment by TiagoSilvaPereira** [comment]
@d4rkr3pt0r that is strange, I have never seen this before. Is it possible to send a video showing it happening?

**Comment by TiagoSilvaPereira** [comment]
Closing for now... please feel free to call me on email with more details if this happens again: contact@vemto.app
