### ISSUE TITLE
laravel-ui templates encode input value attribute twice

### ISSUE THREAD

**Issue by luttje** [TiagoSilvaPereira/vemto-issues#291]
**Describe the bug**
When using special html characters in input, the laravel-ui templates in Vemto encode edit fields twice (once on the resource page using blade {{ and }} and once in the `components/inputs/basic.blade.php`).

**To Reproduce**
1. Create a project which has at least one CRUD resource with a string input field
2. Generate it using the laravel-ui blade templates, view the `form-inputs.blade.php` of this resource:
![image](https://user-images.githubusercontent.com/2738114/161428751-a3ebdf3d-69f3-40a3-b654-393bcd6fae75.png)
4. Start a local webserver
5. Browse to the website and insert "Lutt's Test"
6. View the edit page of this newly added resource:
![image](https://user-images.githubusercontent.com/2738114/161428556-2e11f48a-5aa0-4d16-9fa2-9ab4948110b5.png)
7. View the page source and you'll see the ampersand is escaped:
![image](https://user-images.githubusercontent.com/2738114/161428639-7c77796c-b892-42bc-a301-1de74b6a0259.png)

**Expected behavior**
When passing data to the x-inputs.text component I expect what I give to only be escaped once (by blade)

**What I think is causing this**
The input value is escaped both in `components/inputs/basic.blade.php` and the resource form-inputs.blade.php

**Workaround/fix**
Pass the data to the component without using blade's `{{ }}`, but with:
![image](https://user-images.githubusercontent.com/2738114/161428767-cbf4cc6d-7297-4d43-b156-e73f15057693.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @luttje thank you for reporting, I'll check it asap

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
