### ISSUE TITLE
There seems to be a issue with the language file

### ISSUE THREAD

**Issue by precamp-io** [TiagoSilvaPereira/vemto-issues#295]
This is typically one example of the titles crud.campaign_boards_cards.index_title that's not displaying. Its typically on most pages like this

In the lang/crud.php

    'campaign_boards' => [
        'name' => 'Campaign Boards',
        'index_title' => 'CampaignBoards List',
        'new_title' => 'New Campaign board',
        'create_title' => 'Create CampaignBoard',
        'edit_title' => 'Edit CampaignBoard',
        'show_title' => 'Show CampaignBoard',
        'inputs' => [
            'name' => 'Name',
            'archived' => 'Archived',
            'userid' => 'Userid',
            'from_template' => 'From Template',
        ],
    ],

**Comment by TiagoSilvaPereira** [comment]
Hi @precamp-io I'm not sure I understand the problem... could you please share the project?

**Comment by TiagoSilvaPereira** [comment]
Hi @precamp-io I checked your project here and it correctly generated the translations. Please check if you generated the code again after adding a new CRUD, and if there is no cache issues (not related to Vemto, but with Laravel):

![image](https://user-images.githubusercontent.com/11933789/162210544-5e60e957-71d0-4cbf-a359-8aeb03f537f7.png)
