### ISSUE TITLE
Bottom right green popup on Delete only showing on the first delete

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#296]
Vemto 1.1.2 and 1.1.3
Windows 10

I have noticed that when you delete an item in any of the generated CRUDs, the bottom right green "success"  popup will only show on the first deletion.

**Comment by Benoit1980** [comment]
![1](https://user-images.githubusercontent.com/6231274/165345972-70abbcf7-c765-4cca-bdbe-c08029ac3c70.jpg)


I am adding an image that shows a notification error

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
