### ISSUE TITLE
Questionmark Tips do not work on Mac

### ISSUE THREAD

**Issue by martin-masterclass** [TiagoSilvaPereira/vemto-issues#298]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/64164118/163820165-c738b994-4e74-4f82-9171-a0b4c2c995d1.png">

**Comment by TiagoSilvaPereira** [comment]
@martin-masterclass could you please give more details? For example a video or a screenshot. Tested in a mac here and it worked well

**Comment by martin-masterclass** [comment]
for example, when I click on the question mark here:
[image: image.png]
It just CHECKS the checkbox, but it does not show me any help text. I
tested it on my MacBook Pro from 2019 with Intel chip and as well with my
iMac from 2021 with an M1 chip.

I think the “label” of the field might be too long and overlap with the
question mark.

**Comment by TiagoSilvaPereira** [comment]
Ah got it... these question marks are not clickable... just pass the mouse on top of it to see the info:

![image](https://user-images.githubusercontent.com/11933789/163873914-9070ced7-0e39-4e1e-90cd-9945fc4d6be9.png)

**Comment by martin-masterclass** [comment]
Ah me desculpe, mas o mouseover também não funciona. (Superior, Direita,
Inferior, Esquerda)
Nenhum texto é aberto. Acredito que seria importante.

**Comment by martin-masterclass** [comment]
Testado no iMac M1
