### ISSUE TITLE
Show project name in top green bar

### ISSUE THREAD

**Issue by martin-masterclass** [TiagoSilvaPereira/vemto-issues#300]
Hi, I have a proposal for the app.
I realized, that when I work with different projects, that it would be good during the work on a project to know which project you are working on currently.

Maybe it is possible to show the current project name in the top green bar of Vemto?
Regards, Martin

<img width="903" alt="image" src="https://user-images.githubusercontent.com/64164118/164397343-f4f48b2b-9878-4f5b-a068-57a1e9ef3d7e.png">

**Comment by TiagoSilvaPereira** [comment]
Hi @martin-masterclass Vemto show the current project in the status bar:

![image](https://user-images.githubusercontent.com/11933789/164473980-e6a08a27-0a36-4d96-9e86-17e021be9481.png)

**Comment by martin-masterclass** [comment]
Ah Thanks!! 😄
