### ISSUE TITLE
Relationship issues with version 1.1.3

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#304]
Hi Tiago,

I am attaching as many screenshots as psosible.

In short, when I add a category relationship to an article table/model, in the article crud, when selecting the category and saving the data, I am getting an error 500.

![1](https://user-images.githubusercontent.com/6231274/164944862-700def50-93a6-436d-ae38-e0003ab1ad6f.jpg)
![2](https://user-images.githubusercontent.com/6231274/164944864-a20e1026-197c-487d-97b2-24de6019e40c.jpg)
![3](https://user-images.githubusercontent.com/6231274/164944865-a69c3d06-7cbd-49ef-85d8-74d962db94a5.jpg)
![4](https://user-images.githubusercontent.com/6231274/164944866-556e7c55-7747-4a25-9f76-cedb87238404.jpg)

I tried to regenerate the entire app with "force overwrite files" and whatever I could tick, but same issue.

Thanks

**Comment by TiagoSilvaPereira** [comment]
Hi @Benoit1980 as the error message says: "Field **category** doesn't have a default value"... Seems you created a non-nullable "category field" and are trying to save data without filling this field (for example, you didn't add an input for this field). As you already have a **category_id** field for your relationship, seems this field is unnecessary. So you can just remove it.

Closing here as it is not a Vemto bug.

![image](https://user-images.githubusercontent.com/11933789/164971285-8c191018-7ec9-4cc8-ad44-6f850a021fb8.png)
