### ISSUE TITLE
Seeder changes are not being detected by Vemto 1.1.3

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#307]
Hi Tiago,

On windows 64bit, Vemto 1.1.3, when you edit the factorie's files from an external PHP software, the changes are not detected inside Vemto:

![1](https://user-images.githubusercontent.com/6231274/165130124-0a24ecc4-58c0-48df-af41-5f0ca3d5bb47.jpg)
![2](https://user-images.githubusercontent.com/6231274/165130129-7a214313-e29f-4e49-9469-f25385a18c98.jpg)
![3](https://user-images.githubusercontent.com/6231274/165130136-bf9b4788-7382-4c57-a2c4-e9edf005cbaa.jpg)

Thanks

**Comment by TiagoSilvaPereira** [comment]
Hi @Benoit1980, not a Vemto bug... probably you clicked on "Untrack File"... clicking on that, you are just saying to Vemto: Stop tracking Vemto changes in this file on the next code generation
