### ISSUE TITLE
Field set to Text keep being reset to size 255

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#310]
Hi Tiago,

Vemto 1.1.3
When you set a field to TEXT and regenerate the app, the software keeps resetting the field to size 255 and string. I checked the validation
![image](https://user-images.githubusercontent.com/6231274/165565844-3f1f333e-b116-42e4-8bf9-4b58beffaade.png)

They are set to TEXT
![image](https://user-images.githubusercontent.com/6231274/165566083-0f4b20fa-4cdc-4e8b-b5e5-855f8ff89642.png)

But after generating the app the fields keep coming back to this:
![image](https://user-images.githubusercontent.com/6231274/165566257-684e25b0-5e45-447e-a88a-6d92107d5aec.png)

Thanks.

**Comment by TiagoSilvaPereira** [comment]
Fixed on Vemto 1.1.9
