### ISSUE TITLE
Problem with validation when uploading images

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#311]
Vemto 1.1.3

When creating an image field, the software sets the field type automatically to "string"

The problem is that when you try to upload an image, it asks for a string.

The only way around is by replacing the validation to:
image | max:1024

But there is an issue, when generating the app, the field comes back to "string". I had the problem all day on multiple CRUDs.

![image](https://user-images.githubusercontent.com/6231274/165568959-e251b3e1-e8b1-47b2-8bc1-e2733218d0f0.png)

![image](https://user-images.githubusercontent.com/6231274/165571385-0d8d1985-c962-4a20-bbf2-2c2343d6c0ca.png)

**Comment by TiagoSilvaPereira** [comment]
Fixed previously
