### ISSUE TITLE
Editing web.php routes is not being detected by the app

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#312]
Vemto 1.1.3

I just spend an entire night building my routes, to find out that regenerating the app with a new model/database wipes them out without prior warnings.
The app is not detecting the changes and not showing you the typical "compare differences" panel.

I have added the below commands in the command plugin to update the route cache(last command from the list).
php artisan cache:clear
php artisan view:clear
php artisan config:clear
php artisan config:cache
php artisan route:cache

You could untick the "route" tick box but, it is useful to see the differences instead because you can then copy/paste the change in your IDE rather than trying to rewrite it each time.

**Comment by TiagoSilvaPereira** [comment]
@Benoit1980 tried it here, but worked well... maybe you checked "Force overwrite files"?

![image](https://user-images.githubusercontent.com/11933789/165773594-e92491be-367d-4197-87a4-0ba55cb2afdb.png)

![image](https://user-images.githubusercontent.com/11933789/165773743-4988ea4e-fa82-4c67-8c07-6d43c7baf4cc.png)
