### ISSUE TITLE
Performance issues with more than 20 entities

### ISSUE THREAD

**Issue by marvin-thiel** [TiagoSilvaPereira/vemto-issues#317]
The performance quickly degrades after adding 20 entities or more. The frame rate of the schema editor gets worse and clicks take up to a second to register.
Perhaps an option for disabling animations could be added, maybe that would help a bit already.

 - OS: Linux Mint 20
 - i5 from ~2016
 - 16GB RAM
 - Version 1.1.4

**Comment by TiagoSilvaPereira** [comment]
@marvin-thiel did it worked with ```--ignore-gpu-blacklist```?

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of response. Please feel free to open it again if necessary
