### ISSUE TITLE
[BUG] Vemto cannot find installed composer

### ISSUE THREAD

**Issue by peterjumpnl** [TiagoSilvaPereira/vemto-issues#32]
**Describe the bug**
At generating code, composer is checked on the system.
I have composer installed and can use it from the terminal, but in Vemto I get a bug report.
![image](https://user-images.githubusercontent.com/25691761/98408551-9c439480-2071-11eb-8193-9a1e4dd19509.png)

I am working on a Windows 10 desktop with Vemto 0,57.
Installed composer: 1.10.x

**Comment by peterjumpnl** [comment]
Hmm, by configuring the composer path myself, I got it fixed.

**Comment by hasanslaravelproject** [comment]
Would you please, write the correct and full path for windows10? I got the same error. Please, write in details. Thanks
