### ISSUE TITLE
Update User model file even if the code changed

### ISSUE THREAD

**Issue by noge075** [TiagoSilvaPereira/vemto-issues#322]
**Describe the bug**
On generate code always rewrites User model even if you changed the code.

**To Reproduce**
1. Generate code
2. Add a new method to the code
3. Generate code again (be sure force overwrite files is unchecked)

**Expected behavior**
Only change User model code if it is untouched.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.4

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.5
