### ISSUE TITLE
Error when testing trial: all diagram lines missing

### ISSUE THREAD

**Issue by jay2success** [TiagoSilvaPereira/vemto-issues#323]
Hello,

Thanks for building this amazing app.
I have about 53 entities in 1 project.
When i reload it again, this error happens.
The issue on diagram is there is no line connecting entities.
When i edit 1 entity, example adding field, the error shows again.
Hope this can be solved to improve the app's stability.
Thanks.

```
TypeError: Cannot read property 'entity' of null
    at app://./js/project_schema.764bbb92.js:1:103631
    at Array.forEach (<anonymous>)
    at app://./js/project_schema.764bbb92.js:1:103583
    at Array.forEach (<anonymous>)
    at o.getConnections (app://./js/project_schema.764bbb92.js:1:103376)
    at o.<anonymous> (app://./js/project_schema.764bbb92.js:1:102671)
    at Array.<anonymous> (app://./js/chunk-vendors.6b4aecd2.js:620:12909)
    at dt (app://./js/chunk-vendors.6b4aecd2.js:620:12304)
```

---

vemto 1.1.4
Electron 8.5.5
win32 10.0.19044
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @jay2success could you please share your .vemto file?

**Comment by jay2success** [comment]
Hi, 

Thanks but i have solved it.
I have export the project previously and i try to import it and it's working again.
Will do more tests on this trial period.
Thanks again.
