### ISSUE TITLE
Out of range on decimal field seeders

### ISSUE THREAD

**Issue by noge075** [TiagoSilvaPereira/vemto-issues#324]
**Describe the bug**
When you create a decimal type of field the faker's randomNumber method can be out of range in the model factory.

**To Reproduce**
1. Create any unsigned decimal field for example: P=8 D=2
2. Run seeder
3. You may get an error message like:  Numeric value out of range: 1264

**Expected behavior**
Use faker's randomFloat(P) method instead.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.4

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
