### ISSUE TITLE
Toast notifications stops working after first page load when Hotwire Turbo is enabled

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#325]
The toast notification success messages error out after the first time you create or update a record if Hotwire Turbo is enabled.  

**To Reproduce**  

1.  Generate a project with Hotwire Turbo enabled
2.  Generate some CRUD pages
3.  Open any Create or Update page and add or update a record (the success notification appears as expected)
4.  Create or Update another page and no Toast notification appears.  Chrome DevTools reports that the "Identifier 'notyf' has already been declared".   Below is a screenshot of the full error:

![](https://user-images.githubusercontent.com/20197966/169919055-7f6e7f1e-0e04-4b7f-a9f4-2d16d139a2ef.png)

**Expected behavior**  
I expected the toast success notification to appear after each create or update without having to click on the browser page refresh to do a full page refresh since Hotwire Turbo was enabled.

**Additional context**  
I suspect this is not so much a Vemto app issue, but a compatibility issue between Hotwire Turbo and Notyf (https://github.com/caroso1222/notyf), two scripts used to generate Vemto apps, as reported here caroso1222/notyf#96?

**Comment by TiagoSilvaPereira** [comment]
Hi @relayer464 thank you for reporting, we are already fixing it through #296

**Comment by relayer464** [comment]
Sorry I missed that one.  Thanks!

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.1.9
