### ISSUE TITLE
Vemto can't create a full Laravel project

### ISSUE THREAD

**Issue by salar-rastari** [TiagoSilvaPereira/vemto-issues#326]
I'm using Vemto Trail version and tried to create a project with a few sample models and views.
I faced these warnings when I clicked Generate:

`.env.example file not found. Skipping .env file generation`
`composer.json file not found. Skipping editing composer packages`
`composer.json file not found. Skipping composer install`
`Composer Packages not installed. Skipping php artisan storage:link`
`Composer Packages not installed. Skipping php artisan ui bootstrap --auth`
`Composer Packages not installed. Skipping php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"`
`package.json file not found. Skipping editing NPM packages`
`package.json file not found. Skipping npm install`
`package.json file not found. Skipping npm run dev`
`There aren't changes to the composer.json file. Skipping composer dump-autoload`

![image](https://user-images.githubusercontent.com/11897664/170842890-31bf2aa1-9a5e-47ea-afd5-2c76ebe2eef4.png)
![image](https://user-images.githubusercontent.com/11897664/170842903-ab1051cc-d6fe-413a-97a7-f84f7e6526c2.png)
![image](https://user-images.githubusercontent.com/11897664/170842913-c97a5fb6-448f-4640-83f8-e65cb9806f9d.png)
![image](https://user-images.githubusercontent.com/11897664/170842918-a0741136-6f57-4d40-bbaa-5ff16bf26b39.png)

and these are the folders I get:
![image](https://user-images.githubusercontent.com/11897664/170842857-0f7eef27-34b0-472d-8114-961f790e2b45.png)

thanks.

**Comment by TiagoSilvaPereira** [comment]
Hi @salar-rastari is **git clone** enabled on your Code Generation - Advanced Settings?

**Comment by salar-rastari** [comment]
Hi @TiagoSilvaPereira thanks, I enabled the git and it solved.
