### ISSUE TITLE
It is possible to create a Pivot Crud for a morphToMany relationship

### ISSUE THREAD

**Issue by caolier** [TiagoSilvaPereira/vemto-issues#331]
Hi!,
I'm new with Vemto, nice tool!
I'm practicing with the schema for Breeze permission model, but I can't find the way to show the list of roles into edit user.
In components aren't options for polymorphic relations.  Is it a way to do it?

thanks again, great app

**Comment by TiagoSilvaPereira** [comment]
Hi @caolier it is not possible yet with Vemto, you would need to do it manually... It is on my plans to add components for Polymorphic relationships.

Best regards
