### ISSUE TITLE
where is Array data type?

### ISSUE THREAD

**Issue by d4rkr3pt0r** [TiagoSilvaPereira/vemto-issues#332]
Can anyone tell me how to cast fields as array in Vemto? Why array isn't available to select on data types list?

**Comment by TiagoSilvaPereira** [comment]
@d4rkr3pt0r Vemto follows Laravel structure... there is no Array field type for Laravel migrations, but probably what you are searching for is the Enum type.

**Comment by d4rkr3pt0r** [comment]
@TiagoSilvaPereira I was talking about [this](https://laravel.com/docs/9.x/eloquent-mutators#array-and-json-casting)
