### ISSUE TITLE
VEMTO configuration does not work on my Macbook

### ISSUE THREAD

**Issue by ChristianEW26** [TiagoSilvaPereira/vemto-issues#334]
My VEMTO configuration does not work on my Macbook.

I have already tried several ways, but none work!

I made a screencast here 👍 

https://share.getcloudapp.com/o0uGv5Ab

Thank you for advance

**Comment by TiagoSilvaPereira** [comment]
Hi @ChristianEW26 the problem is that you are copying the path with the binary name, but Vemto expects only the folder portion... For example, if your ```which composer``` command results into ```/usr/bin/composer```, you can copy only ```/usr/bin``` to the Vemto settings, without the binary name at the end of the command
