### ISSUE TITLE
Code generation incomplete

### ISSUE THREAD

**Issue by karimamkar** [TiagoSilvaPereira/vemto-issues#335]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
Code generation blocks if the npm run dev is used

**To Reproduce**
just generate code from a project (Laravel/framework version 9.18)

**Expected behavior**
continue code generation
i think it's due to the new VITE tool introduced in laravel

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
no aditionnal contexte

**Comment by TiagoSilvaPereira** [comment]
Hi @karimamkar we are checking this, thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
@karimamkar please upgrade to Vemto 1.1.6 for a temporary solution... Vite support will come once the Laravel team launch the Jetstream Vite support (they said it is coming next week)

**Comment by TiagoSilvaPereira** [comment]
@karimamkar please upgrade to the latest Vemto version to completely solve this issue
