### ISSUE TITLE
[BUG] Missing validation settings

### ISSUE THREAD

**Issue by buckhornmktg** [TiagoSilvaPereira/vemto-issues#34]
**Describe the bug**
When an image field is added the validation settings disappear. 

**To Reproduce**
1. Add an image field as a standalone field, input name is the same as the field name. (Linked to model field option doesn't work.)

2. Click the validation tab and the page is blank.

3. Remove the picture field and click validation tab again and the settings will be back.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by buckhornmktg** [comment]
Actually, this may be happening with any standalone field.

**Comment by TiagoSilvaPereira** [comment]
Hi @buckhornmktg thank you for reporting it, I'll fix it for the next Vemto version. Cheers

**Comment by TiagoSilvaPereira** [comment]
Hi @buckhornmktg I just fixed it on **Vemto 0.5.9**
