### ISSUE TITLE
When running a project, files are served from the old (wrong) location after having changed the Project Folder

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#346]
**Describe the bug**
When running a project, files are served from the old (wrong) location after having changed the Project Folder

**To Reproduce**
1. Start a new project with Project Folder "X"
2. Generate the code
3. Run the project (no issues)
4. Change the Project Folder to "Y"
5. Generate the code, the code goes into folder "Y", correct
6. Run the project -> the project is served from the old folder, folder "X", incorrect

**Expected behavior**
When running a project, it should be served from the current project folder

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.1.8

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
I believe the problem was happening due to some cache issue... please feel free to reopen the issue if it happens again
