### ISSUE TITLE
When having a model named "Education" with table "educations", the seeder will fail because it attempts to use table name "education"

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#347]
**Describe the bug**
When having a model named "Education" with table "educations", the seeder will fail because it attempts to use table name "education"

**To Reproduce**
1. Start a new project
2. Add a new entity named "Education", table name by default = "educations"
3. Generate the code
4. Run, with migrations and seeder
5. The seeder fails because it incorrectly attempts to use table "education"

**Expected behavior**
The seeder should use the table name from the entity settings (default or set by user), not assume other table name

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.1.8

**Additional context**
Manually setting the table name to "education" in the entity settings will fix the issue, but it would be better if the seeder uses the table name that is already defined in the entity settings.

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad thank you for reporting, I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on Vemto 1.1.9
