### ISSUE TITLE
User::hasPermissionTo() issues after unticking policies and permissions

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#349]
Vemto 1.1.8

I generated a project with the permissions and policies using Breeze and Tailwind CSS.
The permissions and policies made the app a bit too complicated for my project so I unticked them both. 
Regenerated the project and now I am having 2 errors.

Command failed: "C:\laragon\bin\php\php-8.1.2-Win32-vs16-x64\php" artisan migrate:fresh --seed
![Screenshot 2022-07-19 235738](https://user-images.githubusercontent.com/6231274/179855594-6d5acd60-d572-4143-a7fb-2fc67a5f992b.jpg)

 (BadMethodCallException(code: 0): Call to undefined method App\\Models\\User::hasPermissionTo() at C:\\laragon\\www\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php:71)

**Comment by TiagoSilvaPereira** [comment]
@Benoit1980 probably some problem with composer cache... please try ```composer dump-autoload```
