### ISSUE TITLE
Migrations not being generated

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#350]
Vemto 1.1.8

Windows 10.

I deleted 2 columns from one table, regenerated my app with the below settings ticked, the migration is not generated, therefore I am unable to upload the changed to the remote server.

![1](https://user-images.githubusercontent.com/6231274/179958901-4797371c-c909-444b-9272-a4f215e8d015.jpg)
![2](https://user-images.githubusercontent.com/6231274/179959010-2c0d0411-a986-487d-8aa2-af18ac4b64cb.jpg)

Where I am confused is that I was sure that in an earlier version the "Generates Migration" tick box was called "Do not generate migration".

**Comment by Benoit1980** [comment]
From what I see, It did not generate an update migration, instead it generated a full new migration. But it is not being picked up on the remote with php migrate artisan.
Also regenerating a previous migration is dangerous as the remote data will be deleted, it should be an update on the old migration instead.

**Comment by TiagoSilvaPereira** [comment]
Hi @Benoit1980 Vemto does not generate update migrations, for now, please use Vemto only for Bolerplating new projects. For changing migrations, the correct is to make it manually. I'm planning to make this possible with Vemto v2, but it is a complex task and not possible yet.

**Comment by Benoit1980** [comment]
Oh I see, sorry I did not know.
Will Vemto see the new migrations if created through my IDE?

**Comment by TiagoSilvaPereira** [comment]
Hi @Benoit1980 no that is not possible yet... it will only be possible on Vemto 2.x, as it is a highly complex feature and I"m still researching better ways to do it. For now, the recommended way for using Vemto with production projects is to disable migrations generation and use it just to generate new modules

**Comment by Benoit1980** [comment]
Hi @TiagoSilvaPereira Ok thanks.
Will the 2.x come out this year?

**Comment by TiagoSilvaPereira** [comment]
@Benoit1980 I have no ETA yet, as Vemto 2.x is still under research

**Comment by Benoit1980** [comment]
Thanks Tiago :-)
