### ISSUE TITLE
Image upload bug on update validation

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#352]
Vemto 1.1.8

Windows 10

When creating a CRUD with image upload, on the update form, even if the image is already uploaded, it still requires an image to be re-uploaded(it does not take notice the previous image in the validator but shows it in the preview) when you edit a record.

**Comment by Benoit1980** [comment]
To fix the issue, when selecting an image upload field in Vemto, the rule should be changed from "required" to "sometimes". This will enable the update validation to pass.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.1
