### ISSUE TITLE
Filament admin panel doesn't load images!

### ISSUE THREAD

**Issue by salar-rastari** [TiagoSilvaPereira/vemto-issues#355]
I pushed my codes to the server and everything worked fine except loading images, but it works on the local.
The filament admin panel are using "http://localhost:8000/" instead of the domain address, so is there any solution for that?

![image](https://user-images.githubusercontent.com/11897664/181935950-3bb42422-a67f-4fee-8de7-b418ee933280.png)

thanks

**Comment by TiagoSilvaPereira** [comment]
Hi @salar-rastari I'm closing as it is not a Vemto issue... please check if your .env is using the correct URL endpoints
