### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hasanslaravelproject** [TiagoSilvaPereira/vemto-issues#36]
I found this error while run the code. I installed npm  and added the path inside environment variable.

 Error: Command failed: "npm" -v internal/modules/cjs/loader.js:883 throw err; ^ Error: Cannot find module 'C:\Users\Lizaa\AppData\Local\Programs\vemto\node_modules\npm\bin\npm-cli.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }

Sorry, Vemto requires npm installed in your system. Please check if npm is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page

**Comment by hasanslaravelproject** [comment]
Ohhh!!! I got the solution the following way.
copy  'node_modules' folder 
from C:\Program Files\nodejs 
and paste it inside npm folder
C:\Users\Your_user_name\AppData\Roaming\npm

Thanks.

**Comment by TiagoSilvaPereira** [comment]
Hi @hasanslaravelproject thank you for reporting and posting the solution. I'll close for now. If you have any problem, please feel free to open another issue here. Cheers
