### ISSUE TITLE
The detail-form ignores the settings for onCreate/onEdit and shows all fields on the input form

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#360]
**Describe the bug**
When opening the detail-form, it shows all fields on the input form, including the fields that has unchecked the "On Create" and "On Update". So it seems it ignores those settings, confirmed by looking at the template code (Tailwind & Jetstream).

**To Reproduce**
1. Create a master-detail CRUD, with some fields unchecked for "On Create" / "On Update"
2. Generate the code and create the master
3. Open the detail form
4. Notice that all fields, also the fields that were unchecked, shows up on the input form

**Expected behavior**
On the details form, only show the fields that have "On Create" / "On "Update" checked.

**Screenshots**
**Original code:**

<% for(let input of this.relatedCrud.inputs) { %>
<% if(!input.isComputed) { %>

<# We'll replace this [INPUT:id] code with input template #>
[INPUT:<$ input.id $>]

<% } %>
<% } %>

**Fix:**

<% for(let input of this.relatedCrud.inputs) { %>
<% if(!input.isComputed) { %>
<% if(input.onCreate || input.onEdit) { %>

<# We'll replace this [INPUT:id] code with input template #>
[INPUT:<$ input.id $>]

<% } %>
<% } %>
<% } %>

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.1.8

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.2.0
