### ISSUE TITLE
Database migration for Fortify is removed after regenerating code

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#361]
**Describe the bug**
When regenerating the code, the database migration for Fortify two-factor-auth is removed.

2014_10_12_200000_add_two_factor_columns_to_users_table.php

**To Reproduce**
1. Run: php artisan vendor:publish --provider="Laravel\Fortify\FortifyServiceProvider"
2. Migrate... all good
3. Regenerate the code in Vemto
4. Migrate
5. Login and go the to user profile
6. An error is displayed that fields are missing (two_factor_secret etc)
7. Check the migrations -> the 2014_10_12_200000_add_two_factor_columns_to_users_table.php was deleted when the code was regenerated.

**Expected behavior**
Don't remove untracked migrations, including the one for Fortify.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 1.1.8

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad Vemto removes this migration because it already adds these fields to the ```create_users_table``` migration.

**Comment by manfredekblad** [comment]
Ok, maybe some issue with that users migration then? 

I get the SQL error "field is missing" when viewing my user profile, unless I run the Fortify migration manually after regenerating the code and deploying to a clean db.

**Comment by TiagoSilvaPereira** [comment]
Please check if you didn't accidentally remove the field from the model, you can compare it with a newly created project (I hope Vemto 2.x will not feature these difficulties as it will correctly handle the migrations and sync the project with them)

**Comment by manfredekblad** [comment]
Could it be, because I created the project 6 months ago?

I just created a new fresh project in Vemto 1.1.8, and the two_factor fields are there. So maybe they were not in the project when I started it 6 months ago.

**Comment by TiagoSilvaPereira** [comment]
@manfredekblad maybe yes, I recommend being careful running Vemto with an old project, as it doesn't understand the project Schema (something that Vemto 2.x should fix)
