### ISSUE TITLE
Validation rules are reset to default after modifying the table structure

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#362]
**Describe the bug**
Validation rules are reset to default after modifying the table structure. Example, one field in my project had a validation as file, max 1024. I manually set it to 50000 and generated code. It stayed at 50000 until I added another field to the table and regenerated the code. As you can see in the screenshot, the 50000 was reset back to default 1024. I did not touch the validation of those fields, so I know this reset was caused by the application.

**To Reproduce**
1. Create a table with a few fields
2. In the CRUD editor, set the validation to file, 50000
3. Generate code, notice the validation rules are correct
4. Add another field to the table
5. Regenerate the code
6. Notice the validation rules for unrelated fields are reset to default for that table/CRUD.

**Expected behavior**
Changing table structure should not impact the validation rules for unrelated fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/2504486/186461128-e890d38d-4039-4d0a-a9e8-c622edba90ca.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.1.8

**Note**
There were other changes as well, such as field labels and placeholders being reset to default.

**Comment by TiagoSilvaPereira** [comment]
@manfredekblad thank you for reporting, we'll check this ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.2.0
