### ISSUE TITLE
Plugins: External links and Download .zip button not working

### ISSUE THREAD

**Issue by curtisbelt** [TiagoSilvaPereira/vemto-issues#363]
**Describe the bug**

- External links do not work - such as the Repository button in plugins or the various documentation links in the Plugin descriptions. I click them, and nothing happens.

- The Download .zip buttons for plugins do not work: I click it, it says "Downloading..." for a couple of seconds, and then returns to "Download .Zip", without any indication of where the file went. I cannot find where the file was downloaded, so I think it did not download at all. I have worked around this by downloading manually from https://github.com/TiagoSilvaPereira/vemto-filament-plugin.

**To Reproduce**
1. Go to Plugins Marketplace -> Select Filament plugin
2. Click on any external link in plugin description, or try to click Download .zip.
4. See that nothing happens when clicking external links, and plugin Zips do not download.

**Desktop (please complete the following information):**
 - OS: Fedora 36 (Gnome 42.4)
 - Vemto 1.1.8 (AppImage)
 
 I am not sure if it's relevant, but note that I run Vemto with `--no-sandbox` flag to workaround this already reported bug: https://github.com/TiagoSilvaPereira/vemto-issues/issues/340.

**Comment by TiagoSilvaPereira** [comment]
@curtisbelt seems there is a bug with recent Gnome versions and Electron, I'll investigate it, thanks

**Comment by TiagoSilvaPereira** [comment]
@curtisbelt 

It looks like some Linux distros are having permissions issues regarding chrome-sandbox. However, disabling sandboxing by default in Electron is not recommended for security reasons (https://www.electronjs.org/docs/latest/tutorial/sandbox), so for now, there are two options:

- Continue running with ```--no-sandbox``` (which can limit some Vemto features)
- Try to fix permissions regarding chrome-sandbox (https://github.com/electron/electron/issues/17972)
