### ISSUE TITLE
Error on Mac when running the project

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#367]
```
Error: timeout exceeded
    at e.exports (app://./js/chunk-vendors.3a07e361.js:80:13835)
    at XMLHttpRequest.y.ontimeout (app://./js/chunk-vendors.3a07e361.js:645:2784)
```

---

vemto 1.1.9
Electron 8.5.5
darwin 21.6.0
Locale: en-US

<img width="863" alt="image" src="https://user-images.githubusercontent.com/2504486/188073470-6d00221e-661b-4538-a37d-cdc6abe85e4c.png">

**Comment by TiagoSilvaPereira** [comment]
Hi @manfredekblad is it happening every time you try to run the project?

**Comment by TiagoSilvaPereira** [comment]
Closing for now due to lack of details... please feel free to open another issue if the problem still happens
