### ISSUE TITLE
On a master-detail form, the datefield is nullable and the user input is blank, but it defaults to current date when saving

### ISSUE THREAD

**Issue by manfredekblad** [TiagoSilvaPereira/vemto-issues#368]
**Describe the bug**
On a master-detail form, the date field is nullable (and empty input) but defaults to current date. It should be set to null (or use the default set on the field in the db).

**To Reproduce**
1. Create a master-detail such as "Profile"->"Experiences" with a nullable date field on the Experiences table, such as "end date"
2. Generate the code and create a profile
3. Add an Experience and leave the "end date" field blank (nullable in db) 
4. Save and observe that the "end date" is set to current date

**Expected behavior**
Any nullable field should be null if the input from user was null (blank).

**Screenshots**
https://www.loom.com/share/dd4a751cba0547738fb5d7e1bbc6626e

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.9.1

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.2.0
