### ISSUE TITLE
Composer --version command failed (for windows10_users)

### ISSUE THREAD

**Issue by hasanslaravelproject** [TiagoSilvaPereira/vemto-issues#37]
![image](https://user-images.githubusercontent.com/46935393/99196465-d6f1af00-278c-11eb-8f46-196e1ef05cf8.png)

**Comment by hasanslaravelproject** [comment]
Hello,
After sometimes, I got the solutions. Hope, It will help you who are facing the same problem.
Solution:
----------------------------------------------------------------------------------------------------------
Step 1:
open a command prompt (cmd) with "run as administrator"
Create a new folder which name is composer in your pc's C -drive.
use can use the following command in cmd terminal.
then you go to that folder.

mkdir c:\\composer
cd c:\\composer

step #2: copy and paste this line 
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

step #3: copy and paste this line: 
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

step #4 : copy and paste this line:
php composer-setup.php'

step #5 : copy and paste this line:
php -r "unlink('composer-setup.php');"

step6: go to C:\composer folder and then create composer.bat file
 and copy and paste the following code:

@ECHO OFF
SET BIN_TARGET=%~dp0/composer.phar
php "%BIN_TARGET%" %*

step 7: copy and paste the following code in your cmd terminal as an administrator:

SETX PATH "%PATH%;C:\composer;" -m

step 8: go to search button and type environment and click "edit the system environment variable"

select the path and click edit button. just like the image that I paste here.
![image](https://user-images.githubusercontent.com/46935393/99197539-69954c80-2793-11eb-9ccb-f33f0ccdbd2f.png)

then click add button and type your composer path name.
as we created a folder which name is composer in c drive. so we will write
C:\composer

you can write your pc's composer path.

step 9: close browser and all files and make a restart your computer.

open command prompt and type composer --version 
and press enter button. now you can see the version of your composer if its installed and run properly.

after restarting your pc, go to your apps and open settings:

and then copy and paste the composer path location. in my case i will write:  just like the image that I paste here.

C:\composer

now you can try to click generator button. I hope it will work properly.
![image](https://user-images.githubusercontent.com/46935393/99197864-584d3f80-2795-11eb-9ae0-f174afdc9cc9.png)

Thanks.
//Hasan

**Comment by TiagoSilvaPereira** [comment]
Thank you @hasanslaravelproject for sharing your solution... soon I'll add something explaining more about Composer on upcoming Vemto documentation... Have a nice day!
