### ISSUE TITLE
Does not run installation of AppImage on Ubuntu 22 

### ISSUE THREAD

**Issue by Odilbukh** [TiagoSilvaPereira/vemto-issues#371]
I already did Right Click > Permissions > Allow executing file as a program

When I double click or Right Click > Run  nothing happens. The installation process does not run. 

Ubuntu 22.04
PHP 8.1
vemto-1.1.9.AppImage (downloaded from https://vemto.app/download)

**Comment by TiagoSilvaPereira** [comment]
Hi @Odilbukh for Ubuntu 22.04, it is necessary to run with the ```--no-sandbox``` param from the command line. I'll update the docs soon to include this detail. I'm already studying a way to avoid this problem with Vemto 2.x
