### ISSUE TITLE
Command failed: php artisan migrate:fresh --seed

### ISSUE THREAD

**Issue by patrickzuili** [TiagoSilvaPereira/vemto-issues#372]
Hi,
Generation went all good.
when running got this error 

Running php artisan migrate:fresh --seed
Command failed: php artisan migrate:fresh --seed
 (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead at /Users/patrickzuili/Desktop/TSI insurance/tsi/vendor/laravel/framework/src/Illuminate/Database/Connection.php:544)
Please check if the database you set is existent or if the migrations are correct. We recommend running php artisan migrate:fresh --seed inside the project folder to see what errors are happening

**Comment by TiagoSilvaPereira** [comment]
Hi @patrickzuili, the problem is that you are using a primary key that is nullable, and this is not allowed by your database engine. Please remove nullable from all your PKs
