### ISSUE TITLE
scaffold with filament and jetstream

### ISSUE THREAD

**Issue by spham** [TiagoSilvaPereira/vemto-issues#375]
hi
can you tell me how to make a scaffold with default filament admin panel ?
and if it possible to have one for regular user and one for admins users ?

regards

**Comment by TiagoSilvaPereira** [comment]
Hi @spham, you can do it by installing the Filament plugin. It is currently impossible to generate multiple Filament admins from Vemto, but you could try developing two separate projects and mixing them together.

**Comment by spham** [comment]
but it's not work, how to enable this ?

**Comment by TiagoSilvaPereira** [comment]
Hi @spham, after installing the plugin, go to its settings page and configure the CRUD applications you want to generate Filament pages (please notice you need to add CRUD apps to your project before it). Then, generate the code and open the /admin URL (you can see more instructions in the Filament plugin main page)
