### ISSUE TITLE
install issue on linux

### ISSUE THREAD

**Issue by spham** [TiagoSilvaPereira/vemto-issues#377]
hi
not found npm or node

`Sorry, Vemto requires npm installed in your system. Please check if npm is globally available on your PATH environment variable, or add its path to the main settings on Vemto Home Page`

but it installed
which node and npm return

- /home/pham/.nvm/versions/node/v18.9.1/bin/npm
- /home/pham/.nvm/versions/node/v18.9.1/bin/node

it should have any button to test if it ok, because ,now must leave settings, and go in project and start.

**Comment by TiagoSilvaPereira** [comment]
Hi @spham please try adding the NPM path to the Vemto settings and restart it, as shown in the docs: https://vemto.app/docs/1.x/configuration
