### ISSUE TITLE
UUID's not supported in templates

### ISSUE THREAD

**Issue by luttje** [TiagoSilvaPereira/vemto-issues#378]
**Describe the bug**
Related models with UUID's cause a browser error when you click 'Detach' in views with 'Details for BelongsToMany Relationships'

The error I get is: `identifier starts immediately after numeric literal` which is caused by: `detach(d6d5f032-4d71-11ed-bdc3-0242ac120002)`

The problem is that a UUID cannot be passed without being put into a string.

The template should be changed from:
`wire:click="detach({{ $itemProperty->id }})"`

To:
`wire:click="detach('{{ $itemProperty->id }}')"`

**Comment by TiagoSilvaPereira** [comment]
@luttje thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.1
