### ISSUE TITLE
BelongsToMany template generates incorrect Livewire component

### ISSUE THREAD

**Issue by luttje** [TiagoSilvaPereira/vemto-issues#379]
I have an Item model that relates to ItemProperty through a pivot table. I created a CRUD for the Item and added a 'Details for BelongsToMany Relationships' view. The generated code was incorrect.

In my `ItemItemPropertiesDetail.php` on line 70 (in the save method):
`$this->item->itemProperties()->attach($this->itemProperty_id, [`

Should be:
`$this->item->itemProperties()->attach($this->item_property_id, [`

**Comment by TiagoSilvaPereira** [comment]
@luttje thank you for reporting, I'll check it ASAP

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.1
