### ISSUE TITLE
after update, license is not working :-(

### ISSUE THREAD

**Issue by spham** [TiagoSilvaPereira/vemto-issues#380]
hi

my license not work when launch antoher instance of vemto on same computer

![image](https://user-images.githubusercontent.com/1083631/197530089-bba4582f-de52-470f-8e98-469a3cb709de.png)

![image](https://user-images.githubusercontent.com/1083631/197530149-a676fe02-ecb8-450a-843f-31b34c79815a.png)

**Comment by TiagoSilvaPereira** [comment]
@spham you need to *Vacate* the license from your Dashboard: https://vemto.app/home

![image](https://user-images.githubusercontent.com/11933789/197532227-5149d0f3-11d6-41cc-9382-1cfb8bc1668c.png)
