### ISSUE TITLE
Just a quick question ?

### ISSUE THREAD

**Issue by patrickzuili** [TiagoSilvaPereira/vemto-issues#384]
Its not to report a bug, but more understanding VEMTO by itself in general.

My Goal is to make the user table clickable (hyperlinking) to make it show the read action ?
So went on indexView_Table.vemtl and added @can and href associated before the tr closing this after the tr with </a><@endcan

no errors while compiling but it is not doing it what I wanted so I guess I miss something ?

Thank you for your support

**Comment by TiagoSilvaPereira** [comment]
Hi @patrickzuili, I recommend you check the generated code to see if it was generated the way you want (I highly encourage you to make manual tests before changing the template so that you can be sure if the technique you are trying to implement works)

**Comment by patrickzuili** [comment]
Thank You.
I am having issues while doing the uml and generate everything goes as plan
but when I run it uses uml record name removed from the UML in previous
version. it look like the generated code and Database keep previous
versions and give me errors 1072 key column does not exist in table which
is obvious because removed it in the UML ?

**Comment by TiagoSilvaPereira** [comment]
Hi @patrickzuili, I'm not sure I understood the problem... could you please give more details with screenshots?
