### ISSUE TITLE
error while migration debug working just fine

### ISSUE THREAD

**Issue by patrickzuili** [TiagoSilvaPereira/vemto-issues#390]
Hi I passed the debug status,
while doing a migration on production I am  getting this error while running fine on debug ? 

SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (SQL: create table `users` (`id` bigint unsigned not null auto_increment primary key, `fname` varchar(255) not null, `lname` varchar(255) not null, `primary_phone` varchar(255) not null, `company` varchar(255) not null, `email_verified_at` timestamp not null, `password` varchar(255) not null, `current_team_id` bigint unsigned not null auto_increment primary key, `approved` bigint unsigned not null, `status` varchar(255) not null, `homestatelicensenumber` varchar(255) not null, `licenses` multilinestring not null, `active` tinyint(1) not null, `adjuster` tinyint(1) not null, `team` multilinestring not null, `email` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci') 
I don't see two auto column ? why I am getting this migration error ?

**Comment by TiagoSilvaPereira** [comment]
Hi @patrickzuili you created ```current_team_id``` as a primary key (the correct one is a foreign key)

**Comment by patrickzuili** [comment]
yes but it work in the debug mode ?Sent from my iPhoneOn Nov 14, 2022, at 9:24 AM, Tiago S. P. Rodrigues ***@***.***> wrote:﻿
Hi @patrickzuili you created current_team_id as a primary key (the correct one is a foreign key)
