### ISSUE TITLE
No more need of custom uuid trait

### ISSUE THREAD

**Issue by ziming** [TiagoSilvaPereira/vemto-issues#397]
Laravel 9 now has it's own uuid and ulid trait, we can use that instead of having an extra uuid trait file

https://laravel.com/docs/9.x/eloquent#uuid-and-ulid-keys

**Comment by TiagoSilvaPereira** [comment]
@ziming thank you, I'll add this to the task list

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.1
