### ISSUE TITLE
npm missing script: build

### ISSUE THREAD

**Issue by smarano** [TiagoSilvaPereira/vemto-issues#398]
**Describe the bug**
Fresh installation , win 10 
prohject with laravel 7 

Running npm run build
Command failed: npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stefano\AppData\Roaming\npm-cache\_logs\2022-11-25T18_29_42_635Z-debug.log

![image](https://user-images.githubusercontent.com/6280138/204051561-90a1e4df-92c0-4929-91db-2729e331ad78.png)

---- content of log file ------ 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\DEV\\laragon\\bin\\nodejs\\node\\node.exe',
1 verbose cli   'C:\\DEV\\laragon\\bin\\nodejs\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\read-package-json\read-json.js:281:12
4 verbose stack     at C:\DEV\laragon\bin\nodejs\node-v14\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd C:\DEV\projects\NARCISO\vemto_finanz_friend
6 verbose Windows_NT 10.0.19044
7 verbose argv "C:\\DEV\\laragon\\bin\\nodejs\\node\\node.exe" "C:\\DEV\\laragon\\bin\\nodejs\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 verbose node v14.16.1
9 verbose npm  v6.14.12
10 error missing script: build
11 verbose exit [ 1, true ]

**Comment by TiagoSilvaPereira** [comment]
Hi @smarano, for Laravel 7, please change the Assets Builder from Vite to Mix (but I strongly recommend not starting projects with Laravel 7, we are almost on version 10)
