### ISSUE TITLE
new Breez Route added

### ISSUE THREAD

**Issue by t0nka** [TiagoSilvaPereira/vemto-issues#401]
The new Breeze Release 1.15 shipps a new Profile Route , but every time i generate my code in every project, the breeze profile route will be removed

https://laravel.com/docs/9.x/starter-kits

<img width="704" alt="image" src="https://user-images.githubusercontent.com/4823546/205733886-15f9c79c-8688-4073-a8d3-44776758bb1b.png">

<img width="1584" alt="image" src="https://user-images.githubusercontent.com/4823546/205734469-916eccf6-11df-4ca5-bf60-48fb95ad459a.png">

please update the breeze version and routes

**Comment by TiagoSilvaPereira** [comment]
@t0nka thank you for reporting
