### ISSUE TITLE
Filament Resources not generated when "Auth Scaffold with Jetstream" is selected

### ISSUE THREAD

**Issue by drese** [TiagoSilvaPereira/vemto-issues#402]
When the "Auth Scaffold with Jetstream" option is selected, the 'Filament' directory and the nested resources, filters and traits are not generated. When not selected, they are created as expected.

**Comment by cnngraphics** [comment]
Same issue for me.

**Comment by hubciorz** [comment]
@TiagoSilvaPereira @nicollassilva Any news? Jetstream + Filament is also my setup :(

**Comment by TiagoSilvaPereira** [comment]
@hubciorz @cnngraphics @drese, what version of the Filament plugin are you currently using?

**Comment by TiagoSilvaPereira** [comment]
@hubciorz @cnngraphics @drese, could you please share your project file (.vemto) to email contact@vemto.app? Also, please check if you are using the latest Vemto and plugin versions. We tried to reproduce the issue, but without success

**Comment by TiagoSilvaPereira** [comment]
Closing due to lack of details... please check if your Filament plugins are upgraded to the lastest version
