### ISSUE TITLE
What is this error? Error: timeout exceeded

### ISSUE THREAD

**Issue by ali-safdarii** [TiagoSilvaPereira/vemto-issues#403]
```
Error: timeout exceeded
    at e.exports (app://./js/chunk-vendors.6b4aecd2.js:80:13835)
    at XMLHttpRequest.y.ontimeout (app://./js/chunk-vendors.6b4aecd2.js:645:2784)
```

---

vemto 1.2.2
Electron 8.5.5
win32 10.0.22000
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
@ali-safdarii could you please give more details?

**Comment by ali-safdarii** [comment]
i installed vemto in windows 11 and every a few minutes give me this error, i don know why!

**Comment by TiagoSilvaPereira** [comment]
@ali-safdarii I think it is failing to make some HTTP requests, like loading the application updates, etc... please check if your internet connection is ok, and if the Vemto address (https://vemto.app) is enabled from your firewall and is pointing to the correct server IP: **167.71.110.218**
