### ISSUE TITLE
BelongsToMany livewire component references the incorrect related model name

### ISSUE THREAD

**Issue by xsd08tfu** [TiagoSilvaPereira/vemto-issues#404]
**Describe the bug**
When a BelongsToMany relationship is renamed - for example, you have a model which BelongsToMany instances of the User model, but in this case they are "Approvers" so the relationship is named as such - the Livewire Component Controller template still references the underlying model name, rather than the relationship name as declared on the model.

This can be fixed by creating a custom template and changing the relatedCrudModelPluralCamelCase variable to equal this.relationship.name within the ManyToManyDetailLivewireComponent.vemtl file.

**Comment by xsd08tfu** [comment]
I should add, this is in v1.2.2

**Comment by TiagoSilvaPereira** [comment]
@xsd08tfu thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.1
