### ISSUE TITLE
Does not run in Ubuntu 22.4

### ISSUE THREAD

**Issue by Odilbukh** [TiagoSilvaPereira/vemto-issues#405]
I have download the installer vemto-1.2.2.AppImage

Right Click > Permissions > Allow executing file as a program. Done! 

When I run a command in terminal with --no-sandbox there is error. Please look at the screenshot

![image](https://user-images.githubusercontent.com/22895615/218315868-b34206ef-7833-4de2-9378-cad1ab266460.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @Odilbukh it is necessary to install FUSE on your Ubuntu to run AppImage applications: https://docs.appimage.org/user-guide/troubleshooting/fuse.html
