### ISSUE TITLE
laravel version 11 via composer

### ISSUE THREAD

**Issue by t0nka** [TiagoSilvaPereira/vemto-issues#406]
Vemto Version: 1.3.1

after generating a new projekt, composer update fails,

because of a laravel 11 dependency in composer.json file

**Comment by TiagoSilvaPereira** [comment]
@t0nka sorry for that, I just fixed it. Please just close and open Vemto again and it will stop downloading Laravel 11. If you already generated code, please delete all generated files (including .git) and generate it again
