### ISSUE TITLE
Version 1.3.1 - no migration files a created

### ISSUE THREAD

**Issue by t0nka** [TiagoSilvaPereira/vemto-issues#407]
a new project with laravel 10 fails because of missing /database/migration files of my Entities.

Only

2014_10_12_000000_create_users_table
2014_10_12_100000_create_password_reset_tokens_table
2019_08_19_000000_create_failed_jobs_table
2019_12_14_000001_create_personal_access_tokens_table

are generated

**Comment by t0nka** [comment]
OS: MacOS 13.1

**Comment by TiagoSilvaPereira** [comment]
Hi @t0nka could you please close Vemto, delete all generated files (including .git), open Vemto and generate again?

**Comment by t0nka** [comment]
restartet,
files removed,

but got a error on generating now

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4823546/219775681-4fd06875-092e-4a6e-bf64-aacb31bba053.png">

**Comment by t0nka** [comment]
Parse Error : syntax error, unexpected 'List' (T_LIST), expecting ';' on line 5
  3 | namespace Database\Factories;
  4 |
> 5 | use App\Models\List;
    |               ^
  6 | use Illuminate\Support\Str;
  7 | use Illuminate\Database\Eloquent\Factories\Factory;
  8 |

**Comment by TiagoSilvaPereira** [comment]
I'll bring @nicollassilva to the conversation so he can help to check what is happening. Thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Ah I see what is happening... You created a model called List. It is not possible to create a PHP class called List, as it is a reserved language keyword: https://stackoverflow.com/questions/18794279/trying-to-make-a-class-called-list-but-the-list-function-is-breaking-it

**Comment by t0nka** [comment]
ok, now its working correctly.

i ll close this issue. but @TiagoSilvaPereira , i think an input validation for model names would be nice ;-)
