### ISSUE TITLE
Person model translated to People

### ISSUE THREAD

**Issue by Loukili-Rachid** [TiagoSilvaPereira/vemto-issues#408]
hello @TiagoSilvaPereira 
 this is a small issue I'm using the latest vemto version 
 Laravel 10 
 Windows 11
 when I add a new entity type model "Person" 
 the collection gave me a translation to "People"   
 
![2023-02-20_200933](https://user-images.githubusercontent.com/11983029/220184676-7b4a772f-bed0-437b-b6f5-9b1e82d9d6ee.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @Loukili-Rachid, this is correct... when you create a Person model on Laravel, the table is assumed by default to be called **people**
