### ISSUE TITLE
laravel-ui with Laravel 10 requires laravel-ui v4 instead of v3

### ISSUE THREAD

**Issue by ikkebra** [TiagoSilvaPereira/vemto-issues#412]
I am trying to use laravel-ui as the UI Template with Laravel 10 and it is trying to install laravel-ui v3 ("laravel/ui": "^3.0") which causes an error due to php8.1.  Version 4 of laravel-ui is available now that supports Laravel 10 and php 8.1+

`  Problem 1
	- laravel/ui v3.0.0 requires php ^7.3 -> your php version (8.1.16) does not satisfy that requirement.
	- illuminate/console[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.16) does not satisfy that requirement.`

**Comment by TiagoSilvaPereira** [comment]
Hi @ikkebra thank you for reporting, I'll check this problem ASAP

**Comment by ikkebra** [comment]
Laravel UI version 4 drops support for Laravel 8 and PHP 7.3 & 7.4, so you would need to use version 3 when Laravel 8 is selected. Laravel 9+ requires php8.0+ so version 3 of Laravel UI would only be required for Laravel 8 projects.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 1.3.2
