### ISSUE TITLE
[BUG] MS Windows issues a threat alert

### ISSUE THREAD

**Issue by federicoromani** [TiagoSilvaPereira/vemto-issues#42]
MS Windows issues a threat alert
![image](https://user-images.githubusercontent.com/26388136/100277057-4744c100-2f41-11eb-84a4-b99748289bbd.png)

**Comment by hasanslaravelproject** [comment]
Hello, 
I don't know how much risk on it, but at least I can tell you the process of installation that actually you asked for.
Click the upper arrow mark(^) which is beside discard button. Then you will get two option: keep/learn more.
click on  option(Keep). now it will start downloading vemto software. After completing your download, click on exe files. 
now you will get a new window(windows protected you pc). click on "more info". now  click "run anyway" button if you want to install. Hope, this will help you. Thanks.

**Comment by hasanslaravelproject** [comment]
> MS Windows issues a threat alert
> ![image](https://user-images.githubusercontent.com/26388136/100277057-4744c100-2f41-11eb-84a4-b99748289bbd.png)

Hello Federicoromani ,
I don't know how much risk on it, but at least I can tell you the process of installation that actually you asked for.
Click the upper arrow mark(^) which is beside discard button. Then you will get two option: keep/learn more.
click on option(Keep). now it will start downloading vemto software. After completing your download, click on exe files.
now you will get a new window(windows protected you pc). click on "more info". now click "run anyway" button if you want to install. Hope, this will help you. Thanks.

**Comment by TiagoSilvaPereira** [comment]
Hi, @federicoromani thank you for reporting... This alert is shown because Vemto doesn't have a Windows certificate yet. But don't worry, Vemto doesn't make any dangerous operation. If you want, you can try it on a Virtual Machine before using it on your main machine. Soon I'll acquire the Windows certificate to remove this alert. Thanks
