### ISSUE TITLE
Fail to Generate Codes

### ISSUE THREAD

**Issue by fredyns** [TiagoSilvaPereira/vemto-issues#429]
getting error on ```npm run build```.
even for blank project.
![Screenshot 2023-06-04 153706](https://github.com/TiagoSilvaPereira/vemto-issues/assets/4033019/3db75bcf-f020-4d7b-a9cd-9eca6adb23e7)

**Comment by TiagoSilvaPereira** [comment]
Hi @fredyns, this error is happening due to some changes to Vite. You can do what the error message says: rename postcss.config.js to postcss.config.cjs and rerun code generation. It will probably work

**Comment by fredyns** [comment]
Thank you for your response.
it works!

can't believe there would be breaking update from vite
