### ISSUE TITLE
[BUG] Wrong routes names with non-english Model name

### ISSUE THREAD

**Issue by num3r06** [TiagoSilvaPereira/vemto-issues#43]
**Describe the bug**
I'm italian developer.
I try to use the app for generating model with italian name (singula,plural). 
If i try to change the configuration for model/controller generation some name are changed (in views name or in controller redirect) others none.

**Comment by TiagoSilvaPereira** [comment]
Hi @num3r06 thank you for reporting... could you please send some examples of code so I can check here what is happening? Cheers

**Comment by num3r06** [comment]
Sorry for the incomplete issue report.
So the model's name it's Toponimo plural Toponimi.
I've setting Collection = Toponimi and Table=toponimi. In crud editor i've setting name = Toponimi and Route/Endpoint = toponimi.
In generated code (ToponimoController@index) it's return view('app.toponimos.index', compact('toponimi', 'search'));
while the generated view it's app.toponimos.index. And so on for every function
How it is possible to configure the app for non english use?
Thx

**Comment by TiagoSilvaPereira** [comment]
thank you @num3r06 I just fixed it on **0.6.1**
