### ISSUE TITLE
Filament plugin, not adding dependency to composer.json

### ISSUE THREAD

**Issue by coder36** [TiagoSilvaPereira/vemto-issues#432]
**Describe the bug**
When generating a Filament project, its dependency is not added to composer.json

**To Reproduce**
Starting with a vanilla project, install the filament plugin, select CRUDs and Generate the code.  

composer.json is missing the filament dependency

**Expected behavior**
Composer.json should have: required dependency:`"filament/filament": "^2.0",`

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome

**Comment by TiagoSilvaPereira** [comment]
Hi @coder36 I tested it here and it added the dependency... could you please record a video showing the code generation process?

**Comment by TiagoSilvaPereira** [comment]
@coder36 seems it successfully installed Filament... could you please check if it is inside the /vendor folder?

**Comment by coder36** [comment]
Not inside the vendor folder:  
![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/561451/8a678da6-0dcd-4150-bfb7-b61ae3db5787)

**Comment by coder36** [comment]
composer.json:
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by TiagoSilvaPereira** [comment]
@coder36 could you please try deleting the whole project folder and generating everything again?

**Comment by coder36** [comment]
Apologies @TiagoSilvaPereira  for not getting back.  but...

I deleted the project folder, and get the same issue.

**Comment by TiagoSilvaPereira** [comment]
@coder36 does a new project have the same problem?

**Comment by coder36** [comment]
Hi.. it worked for a new project !  
![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/561451/277d3393-204a-435f-be20-ce83d07c75e6)

**Comment by TiagoSilvaPereira** [comment]
@coder36 Perhaps some data specific to the problematic project has become corrupted. In that case, I recommend trying to install Filament manually, as Vemto will generate the resources for you. I hope this helps
