### ISSUE TITLE
 (PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column

### ISSUE THREAD

**Issue by AdamovicBoban** [TiagoSilvaPereira/vemto-issues#435]
Problem with MariaDB and utfmb4, when the string in the database is set as varchar(191), but when I enable factories and seeders, it tries to insert more than 191 characters. The faker string in the field is set as $faker->text({SIZE}). Can I change the SIZE variable and where? Or how can I modify Vemto to create a string of default length 191?

![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/68257663/320b9b6b-f4f7-48fe-bf17-888c634bb347)

![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/68257663/dd174731-3216-4b4d-a91c-d5be1dc8d31f)

**Comment by TiagoSilvaPereira** [comment]
Hi @AdamovicBoban {SIZE} comes from the field size setting, which is 255 in the image you sent... so you can just change it to 191, or you can replace {SIZE} directly with the size you want: $faker->text(191)
![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/11933789/294f9af9-3632-42f5-b010-3efeeacf5aa4)

**Comment by AdamovicBoban** [comment]
Hi @TiagoSilvaPereira , 

yes, I understand that, but how do I set it so that the standard on Vemto is 191 and not 255. You don't think I should change it manually for each field, do you? :)

**Comment by TiagoSilvaPereira** [comment]
@AdamovicBoban There is no way to specify the default size, as this is the first we've heard of this issue. So yes, at the moment, the only way would be to modify field by field.

**Comment by AdamovicBoban** [comment]
Hi @TiagoSilvaPereira Do it in the next version. When is the next version coming out?

**Comment by TiagoSilvaPereira** [comment]
@AdamovicBoban, no ETA yet, I'm still working on it... version 2 is much more complex than v1, so I'm trying not to pressure myself with a release date... but it is quite advanced now. I hope to launch pre-alpha until September, but no promises yet
