### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kyle032401** [TiagoSilvaPereira/vemto-issues#443]
hi i got some issues about installing laravel nova 
![bug1](https://github.com/TiagoSilvaPereira/vemto-issues/assets/140062905/4d9f533f-f121-4724-ba0e-54b49d069584)
![bug2](https://github.com/TiagoSilvaPereira/vemto-issues/assets/140062905/19794d44-9fe6-4c63-a3f9-02fd28e9bc8d)
![bug3](https://github.com/TiagoSilvaPereira/vemto-issues/assets/140062905/74355b78-11c0-41a2-b836-83ad041fff34)
 
it is still laravel jetstream, it didnt work. I already installed the plugin
![bug4](https://github.com/TiagoSilvaPereira/vemto-issues/assets/140062905/0f747a8c-9505-4c7e-ba97-3285ad13eacd)

**Comment by TiagoSilvaPereira** [comment]
Hi @kyle032401 it is necessary to install Laravel Nova manually. Nova is a paid package, so Vemto can't install it. It only generates the Nova resources.

**Comment by kyle032401** [comment]
Thanks!. I hope next update for vemto is you can create charts (line, bar
and pie graph) and fix the large screen size

**Comment by TiagoSilvaPereira** [comment]
@kyle032401 tank you for your suggestions... could you please explain more about the large screen issue?

**Comment by kyle032401** [comment]
my design is name beside to email (1.png)
when i clicked read icon it shows (2.png)
and when i update it shows (3.png)

my concern is the design of my crud is same to (3.png) as well


Noong Huw, Ago 31, 2023 nang 11:56 PM, sinulat ni Tiago S. P. Rodrigues <
***@***.***> ang:

**Comment by kyle032401** [comment]
when i clicked on search button it happens

**Comment by TiagoSilvaPereira** [comment]
@kyle032401 sorry, seems images were not uploaded. Could you please attach then again?
