### ISSUE TITLE
index page search error with null value

### ISSUE THREAD

**Issue by 5SMNOONMS5** [TiagoSilvaPereira/vemto-issues#447]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
In index page when you search with null value, it appear error , see below 

**To Reproduce**
1. Go to index page
2.  Click search button without any keyword

**Expected behavior**
no error

**Screenshots**
![Screen Shot 2023-09-15 at 10 11 37 AM](https://github.com/TiagoSilvaPereira/vemto-issues/assets/8379901/d12fd028-e551-49d0-8fbf-b90926d01e6d)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: any
 - Version 1.3.3

**Additional context**
This should be discuss about application should be allow search null ( means return all data like you first time visit index page ) or disable button when no text input

**Comment by irafaelfurtado** [comment]
It's true, I have the same issue.
Although it's something simple to solve, it doesn't hurt to give a heads up ;)

**Comment by TiagoSilvaPereira** [comment]
@5SMNOONMS5 @irafaelfurtado thank you for reporting... soon we'll launch Vemto v2 with this issue already solved

**Comment by 5SMNOONMS5** [comment]
thx @TiagoSilvaPereira

**Comment by Ls6375** [comment]
This issue is very easy to resolve for the this current version of Vemto, 
Go to Models > Scopes > Searchable.php, Simply add '?' in the search paramter to allow it to accept null value, in this way, this issues will gonna be sovled. 


![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/57332538/58ae49e8-08ab-4070-836e-160c07b4e8da)

**Comment by 5SMNOONMS5** [comment]
@Ls6375 thx for reply. but still good for author to know, fix will be nice for every project and all new users.

**Comment by TiagoSilvaPereira** [comment]
> This issue is very easy to resolve for the this current version of Vemto, Go to Models > Scopes > Searchable.php, Simply add '?' in the search paramter to allow it to accept null value, in this way, this issues will gonna be sovled.
> 
> ![image](https://user-images.githubusercontent.com/57332538/278220250-58ae49e8-08ab-4070-836e-160c07b4e8da.png)

The problem is that Vemto v1 does not support adding ? character due to some problems in the Template Engine. The fix is coming to v2 with the improved template engine
