### ISSUE TITLE
[BUG] Run::handleError("Trait 'Spatie\Permission\Traits\HasRoles' not found"

### ISSUE THREAD

**Issue by num3r06** [TiagoSilvaPereira/vemto-issues#45]
**Describe the bug**
When i Run after migration an error exception are catched
"Trait 'Spatie\Permission\Traits\HasRoles' not found"
Vemto version 0.6.1
**To Reproduce**
1. Fresh project
2. Create some App and Model
3. Generate and Run

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

**Comment by TiagoSilvaPereira** [comment]
Hi @num3r06 could you please check if the spatie/laravel-permission package was installed on your project? If not, please try deleting the project folder and try generating the code again. By default, Vemto adds laravel-permission to your composer.json then runs composer install to install it, but maybe it did not run correctly in your case.

**Comment by num3r06** [comment]
Yes i did it and works.
I remove vendor folder and re-generate code and all works fine
thx
