### ISSUE TITLE
can't start vemto after fresh install

### ISSUE THREAD

**Issue by gnusam** [TiagoSilvaPereira/vemto-issues#450]
**the bug**
when i launche vemto from a terminal or from my desktop it lauches a white windows and crash. 

**To Reproduce**
Start vemto, see it crash. 
You get the following error in terminal : 

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
17:28:35.086 › Checking for update
17:28:36.283 › Update for version 1.3.3 is not available (latest version: 1.3.3, downgrade is disallowed).
17:28:36.283 › checkForUpdatesAndNotify called, downloadPromise is null
[3579:1020/172837.727780:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
zsh: trace trap (core dumped)  vemto
```

**Desktop (please complete the following information):**
 - OS: Manjaroxfce 23
 - Browser : google chrome Version 118.0.5993.88 (Official Build) (64-bit).
 - Version Vemto 1.3.3 (Latest)

**Additional context**
I got a bit old graphic card, maybe it's an issue for acceleration with vemto ?? 

01:00.0 VGA compatible controller: NVIDIA Corporation GF106GL [Quadro 2000] (rev a1)

**Comment by TiagoSilvaPereira** [comment]
Hi @gnusam please try running it with the ```--no-sandbox``` param

**Comment by gnusam** [comment]
it solved the issue. The app is running fine with this parameter on my system. 

Thanks for your help !

**Comment by gnusam** [comment]
it solved the issue. The app is running fine with this parameter on my system.

Thanks for your help !
