### ISSUE TITLE
License lost after restart vemto app

### ISSUE THREAD

**Issue by cgrauls** [TiagoSilvaPereira/vemto-issues#455]
hi,

when i upload the license in vemto on windows. and close the vemto app. I need to revoke it online and reenter the license in vemto app again.  How can i prevent this?

**Comment by TiagoSilvaPereira** [comment]
Hi @cgrauls, please check if you are opening two Vemto instances simultaneously. Vemto only detects the license in the first instance of the process.

**Comment by cgrauls** [comment]
i think that was the case. closed vempto reopened it add license again. closed it again reopen and now the license seems available. thanks :)
