### ISSUE TITLE
Nova versão prometida

### ISSUE THREAD

**Issue by irafaelfurtado** [TiagoSilvaPereira/vemto-issues#457]
Olá, eu comprei a versão atual na esperança de ter acesso a nova versão, que supostamente iria ser lanada em setembro do ano passado, mas pelo visto não..
Tem data para lançamento a nova versão?
Eu gostei bastante do projeto e queria passar a utilizar sempre, porém muitas das coisas que necessitamos no dia-dia estão apontadas para a nova versão.

**Comment by TiagoSilvaPereira** [comment]
@irafaelfurtado olá, tive alguns atrasos no desenvolvimento da nova versão por problemas de saúde, mas agora estamos muito próximos do lançamento da Pré-Alpha... não vou passar uma data específica ainda para não acontecer o mesmo que anteriormente, mas estamos fazendo ajustes finais e em breve estarei testando o build de produção.

Atenciosamente,
Tiago
