### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by Aksoom-Hussain** [TiagoSilvaPereira/vemto-issues#47]
manage a global variable space like config.constants which can have dynamic fields to add before generation can use in the application anytime anywhere ideal for API packages and gateways 

just create a dynamic page for constants add fields and type and generate the crud to update the constants file
it seems the better alternative to the .env

**Comment by TiagoSilvaPereira** [comment]
Hi @Aksoom-Hussain thank you for reporting. I'm closing as it seems to be a duplicate from #19... By default, Laravel uses .env to manage settings, so it is better to add a dynamic way to manage these .env settings than creating a new way. Have a wonderful day. Cheers
