### ISSUE TITLE
[BUG] port does not change in Metadata tab

### ISSUE THREAD

**Issue by boskiv** [TiagoSilvaPereira/vemto-issues#49]
**Describe the bug**
If I decide to change DB engine from Mysql to Postgres for example, the port has not changed after.

**To Reproduce**

1. Generate project with Mysql Connection
2. Go to `Project settings`
3. Click on the `Metadata` tab
4. Change `Connection` to `Postgres`
5. Port does not change.

**Expected behavior**
Port should adopt

**Screenshots**
![Screen Shot 2020-12-08 at 2 53 16 PM](https://user-images.githubusercontent.com/1939783/101540399-8e7d7980-3965-11eb-86de-c0e81c9a3ce1.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 0.6.2

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.6.3
