### ISSUE TITLE
[BUG] Multi-word resource route names, words are separated by "_" instead of "-"

### ISSUE THREAD

**Issue by rohithmeethal** [TiagoSilvaPereira/vemto-issues#5]
**Describe the bug**
Multi-word resource like `UserType` will have resource name like `user-types.index` but in generated code `user_types`.index is used, that is "_" used instead of "-" in separating words. This leads to route not found issue.

**To Reproduce**
1. Create resource UserType
2. Create CRUD for UserType

**Expected behavior**
No route found issues

**Additional context**
Vemto Version 0.4.14

**Comment by TiagoSilvaPereira** [comment]
Thanks @rohithmeethal  I'll check it

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.4.15
