### ISSUE TITLE
[BUG] Migration fails when using Run command on Generate Code page

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#54]
**Describe the bug**
When I use the Run command on the Generate Code page it fails:

Command failed: "C:\laragon\bin\php\php-7.4.9-Win32-vc15-x64\php" artisan migrate:fresh --seed

I believe the problem is that the ending quotation mark should not include **php** since that is part of the artisan command.  In other words, the ending quotation mark should appear at the end of the file path.  Example:

"C:\laragon\bin\php\php-7.4.9-Win32-vc15-x64"

This isn't a major problem since you can run the command manually at the command line as well. 

**To Reproduce**
1. Go to 'Generate Code'
2. Click on 'Run'

**Expected behavior**
That the the artisan command would execute.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by TiagoSilvaPereira** [comment]
Hi, @relayer464 thank you very much for reporting.

Does it show another error? Or only "Command Failed"? When running the exact same code on the Command-Line, what happens?

I think the problem is not with the quote. For Windows environments, it is necessary to add the quotes precisely like that, otherwise, the command will fail.

Cheers

**Comment by relayer464** [comment]
Here is a screenshot of everything I see after using the Run command.

![image](https://user-images.githubusercontent.com/20197966/102662253-54656200-4133-11eb-970b-187181d0f54f.png)

If I run **php artisan migrate:fresh --seed** it works fine.  

It was my understanding that quotes are typically used around file paths on Windows systems since the file path might contain spaces."  Since **php** is part of the command and not the file path I _thought_ the quote probably needed to go before it.  However, now I see how the **npm** is contained within the quote and that command executes fine, I see your point.

**Comment by TiagoSilvaPereira** [comment]
Hi @relayer464 got it... could you please check if the php version running on Vemto is the same that runs on your terminal and if the installation path is the same? 

Sorry for this inconvenience, unfortunately, the *php artisan* command doesn't write the errors to the **stderr**, so it is hard to understand what is happening when it fails inside *Vemto*.

I'd love to find a way to get the errors and show it directly on the Vemto console as I do with other commands.

Cheers

**Comment by relayer464** [comment]
Yes, the php version running in Vemto and at the terminal are the same.  I am using the php that is installed as part of Laragon.  Here's the path to it:

C:\laragon\bin\php\php-7.4.9-Win32-vc15-x64

I checked the Windows environmental variables and confirmed it is using the same one.

**Comment by TiagoSilvaPereira** [comment]
Hi, @relayer464 got it... when running directly in the terminal, does the Seeders runs correctly too? The majority of fails when running this command is caused by seeding problems.

**Comment by relayer464** [comment]
Yes, when I run **php artisan migrate:fresh --seed** in the terminal both migrate and seeder work correctly.

**Comment by TiagoSilvaPereira** [comment]
Hi @relayer464 sorry for the late, I'm returning to development after the holidays... could you please check if the error generates some log on the laravel.log file?

**Comment by TiagoSilvaPereira** [comment]
Closed due to inactivity
