### ISSUE TITLE
[ENHANCEMENT] Leave previously generated Application code in place (i.e., do not remove) when Generate Code for Application is unchecked

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#55]
**Is your feature request related to a problem? Please describe.**
When you uncheck the Generate Code for an "Application" it doesn't generate that applications code (the expected behavior).  However, when you uncheck Generate Code for an "Application" it also removes those files (the unexpected behavior).   I debated whether to tag this as a Bug or Enhancement, but I went with Enhancement since I am not sure if there is a reason why the files are removed?     

**Describe the solution you'd like**
As a Vemto user I see it as a mean for jumpstarting projects.  I fully expect to have to add and "tweak" code after it has been generated.  For example, on my current project I need to use belongsToMany relationships.  Vemto generates the needed pivot table and references in the related models, which is great.  I then have to modify the controller and blade pages to finish setting up the belongsToMany relations.  By unchecking the Generate Code for a specific "Application" where I made custom modifications, I thought I was safeguarding the controller and blade pages.  However, since they were removed from the application my changes are lost.  I realized that a work-around is to commit them to GIT before regenerating an application, but it would be nice if when you uncheck the Generate Code option for an Application it not generate the code for that Application but **_also_** not remove the code.  

**Describe alternatives you've considered**
As mentioned, the work-around is to use GIT to save changes and then roll back.

**Comment by ballesta** [comment]
Hi,
Could you detail the way of using Git to preserve manual customization of generated code.
I understand from your previous message that you commit customised code before to generate.

Do you 
- commit on a specific "customisation" branch 
- generate code using Vemto 
- commit to "generated" branch
- Merge "customisation" branch on to "generated" and handle potentials git merge conflicts
- ...

Preserving customised code is mandatory, most code generator fail in doing it properly.

Best regards 
Bernard

**Comment by TiagoSilvaPereira** [comment]
Added to the roadmap https://trello.com/b/0MTU9Vyq/vemto-roadmap
