### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by knutdF** [TiagoSilvaPereira/vemto-issues#56]
```
TypeError: Cannot read property 'type' of null
    at a.create (app://./js/project_crud.62d63bba.js:1:26228)
    at app://./js/project_crud.62d63bba.js:1:26110
```

---

vemto 0.6.2
Electron 8.5.2
win32 10.0.18363
Locale: de

**Comment by TiagoSilvaPereira** [comment]
Hi @knutdF thank you for reporting... could you please share more details like:

- A screenshot of your schema
- What type of field are you linking to the select input?

Thanks

**Comment by TiagoSilvaPereira** [comment]
Closing as duplicate from #51
