### ISSUE TITLE
[BUG] Error Call to a member function contains() on string (View: ......\resources\views\layouts\nav.blade.php)

### ISSUE THREAD

**Issue by zebhi** [TiagoSilvaPereira/vemto-issues#59]
**Describe the bug**
Error after Login and accessing http://localhost:8000/home

**To Reproduce**
1. Run Laravel 'http://localhost:8000' and success opening welcome page
2. Login
3. After that it showing error at http://localhost:8000/home

**Expected behavior**
Successful Login and showing the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/7016790/103630690-a0f2cf00-4f74-11eb-8d6b-d8ba0274bb00.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Latest]

**Comment by TiagoSilvaPereira** [comment]
Hi @zebhi thank you for reporting. I recommend removing the ```./vendor``` folder and the ```composer.lock``` then run ```composer install``` to install all dependencies again.

As the error is not related to Vemto, but with the Laravel Permissions package, I'm closing here. But feel free to comment here if you need help.

Cheers
