### ISSUE TITLE
Use related models in relation fields CRUD

### ISSUE THREAD

**Issue by rohithmeethal** [TiagoSilvaPereira/vemto-issues#6]
**Is your feature request related to a problem? Please describe.**
If User has many Cars, currently when creating Car I have to enter user_id in CRUD, which is not practical.

**Describe the solution you'd like**
If User has many Cars, on creating Car I should be able to choose the User from a drop down in CRUD UI.

**Comment by TiagoSilvaPereira** [comment]
Hi @rohithmeethal thank you for your advice. To add a dropdown on relationship fields, please try to use select fields, it will generate the correct relationship dropdown:
![image](https://user-images.githubusercontent.com/11933789/94435485-93f26280-0171-11eb-802e-eac4a3284feb.png)

**Comment by rohithmeethal** [comment]
Thanks :)
