### ISSUE TITLE
[ENHANCEMENT] Clone from custom git repository

### ISSUE THREAD

**Issue by santiaguf** [TiagoSilvaPereira/vemto-issues#60]
When you create a project, vemto gets laravel from github, and then, if you want to use a custom git repo, you lose the changes vemto do to the laravel code. 

it would be nice the option to get laravel from scratch, and then, create the project, so you can put a commit with the changes vemto does

**Comment by TiagoSilvaPereira** [comment]
Hi @santiaguf thank you for your suggestion... I already have plans to add the option to clone from custom git repositories

**Comment by TiagoSilvaPereira** [comment]
Feature added on 0.7.7
