### ISSUE TITLE
[BUG] Incorrect path to view in generated crud when changing the default path

### ISSUE THREAD

**Issue by tkerns** [TiagoSilvaPereira/vemto-issues#61]
**Vemto version 0.6.4**
Inside edit and create views in the generated crud, the include path of the form inputs view is incorrect
For example on the USER model create and edit views inside of views/admin/users
The generated include inside the create and edit views is:
`@include('app.users.form-inputs')`
Should be:
`@include('admin.users.form-inputs')`

(ie **admin** **instead** of app)

**Comment by TiagoSilvaPereira** [comment]
Hi @tkerns thank you for reporting it, I'll fix it for next Vemto versions

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.7.2
