### ISSUE TITLE
[ENHANCEMENT] Add profile management, and migrate from laravel ui to breeze

### ISSUE THREAD

**Issue by tkerns** [TiagoSilvaPereira/vemto-issues#62]
I suggest adding profile management.  I realize this can be done with crud creation, but everyone who logs in needs to have the ability to update their name, email address, and password.
It would be nice to add that out of the box, and add a profile link above the log out link in the user dropdown menu.

You might also consider upgrading your auth to use breeze instead of laravel ui.  I know you have jetstream in your roadmap, but I would suggest breeze over jetstream personally, but maybe give a choice?

**Comment by TiagoSilvaPereira** [comment]
Hi @tkerns thank you for your suggestions. I already have plans to add Breeze, I just not added it to the Roadmap because a forgot to do it haha (when I added Jetstream, Taylor wasn't created Breeze yet). 

Cheers

**Comment by TiagoSilvaPereira** [comment]
Closing as it is already on roadmap
