### ISSUE TITLE
[BUG] Unable to enter settings text after deleting Components

### ISSUE THREAD

**Issue by Parkbyounghyo** [TiagoSilvaPereira/vemto-issues#63]
CRUD Editor 
Unable to enter settings text after deleting Components

**Comment by TiagoSilvaPereira** [comment]
Hi @Parkbyounghyo could you please share more details about the problem?

**Comment by Parkbyounghyo** [comment]
I'm sorry I can't speak English well.
I'll explain as much as possible.
There is no error when adding the left'Components' in the'CRUD Editor' screen, but after deleting the added'Component',
It becomes impossible to change the text of'Lavel' in the'Settings' screen on the right.

**Comment by TiagoSilvaPereira** [comment]
@Parkbyounghyo thank you, got it... I'll check what is happening in that case

**Comment by TiagoSilvaPereira** [comment]
Closing as #52 duplicate... It will be fixed in the next version
