### ISSUE TITLE
[BUG] Vemto 0.7.1 & macOS Mojave

### ISSUE THREAD

**Issue by GlennM** [TiagoSilvaPereira/vemto-issues#64]
**Describe the bug**
Blank screen after update to newest version

**To Reproduce**
1. Make sure latest versionof Vemto is installed
2. Start app
3. Screen is blank

**Expected behavior**
Be able to use Vemto

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14. 6
 - Browser N/A
 - Version Vemto 0.7.1

**Additional context**
I've not updated macOS to latest version because of compatibility with third-party software. Vemto 0.6.3 still runs on this macOS version.

**Comment by tjaoc** [comment]
I have the same problem but in Big Sur.

**Comment by graham-ch** [comment]
Exactly the same issue on Big Sur 11.0.1

**Comment by waltoninternet** [comment]
Same issue on Mac Mojave 10.1.6.  uninstalled and reinstalled previous 0.6.4. Works again, but now the previous version will not accept license - "License already occupied by another computer"

**Comment by TiagoSilvaPereira** [comment]
Hi @GlennM @graham-ch @tjaoc @waltoninternet sorry for it, I just fixed this issue with **0.7.2**. I had a problem with the macOS build that updated a library incorrectly. Thank you for reporting it

**Comment by GlennM** [comment]
Thanks for the quick fix, confirmed that the new version fixes the issue.
