### ISSUE TITLE
[ENHANCEMENT] Incompatible with Laravel Valet?

### ISSUE THREAD

**Issue by tanthammar** [TiagoSilvaPereira/vemto-issues#65]
Unable to "run"
Error:
![image](https://user-images.githubusercontent.com/21239634/104719663-17d65780-572d-11eb-80f8-d79185b02ca3.png)

Unable to go to the url https://vemto.test 
![image](https://user-images.githubusercontent.com/21239634/104720388-4b18e680-572d-11eb-9eac-10908fb6ff99.png)

The project is saved in my Sites folder on macos.
Is Vemto incompatible with Laravel Valet?

I can "generate" without issue.

The .env, database looks ok.

**Comment by TiagoSilvaPereira** [comment]
Hi, @tanthammar thank you very much for reporting. Vemto is currently not directly compatible with Laravel Valet, as it uses the command ```php artisan serve``` to run the application. So, in that case, you need to start the project manually... I'll change this issue from bug to improvement to add Laravel Valet support in the future.

**Comment by tanthammar** [comment]
It's no problem that I can't use the interface to "run" the application. 
But there's something that blocks Valet to display the site.
I get a 404.

**Comment by tanthammar** [comment]
Ah so stupid. I didn't see that the project was generated in a subfolder, that's why I couldn't launch it with Valet :)
