### ISSUE TITLE
[BUG] If you change the table field type, the field options are not changing accordingly.

### ISSUE THREAD

**Issue by Parkbyounghyo** [TiagoSilvaPereira/vemto-issues#68]
Schema Editor - If you change the table field type, the field options are not changing accordingly.

**Comment by TiagoSilvaPereira** [comment]
Hi @Parkbyounghyo thank you for reporting... could you please share more details about the problem like:

- when the problem occurs?
- what was the previous field type?
- what is the new field type?
- what options are not changed accordingly?

Thank you

**Comment by Parkbyounghyo** [comment]
It's a problem for all types.
If you change it after setting the type for the first time, the same problem occurs.
![typeString](https://user-images.githubusercontent.com/27269587/105927784-0889cf00-6088-11eb-89c1-8e4af831f5f7.jpg)
![changeDecimal](https://user-images.githubusercontent.com/27269587/105927814-15a6be00-6088-11eb-8a45-5fd164cdf60a.jpg)
![defaultDecimal](https://user-images.githubusercontent.com/27269587/105927817-163f5480-6088-11eb-984a-f28f7c95f28e.jpg)

**Comment by TiagoSilvaPereira** [comment]
@Parkbyounghyo fixed on 0.7.3
