### ISSUE TITLE
API Only

### ISSUE THREAD

**Issue by boskiv** [TiagoSilvaPereira/vemto-issues#69]
**Is your feature request related to a problem? Please describe.**
As a user, I want to have the ability to generate API only backend

**Describe the solution you'd like**
Possible when I choose UI Template to None or `API Only` no UI template or CSS framework should apply.
Controllers should be API Only, no index, no show methods.
`api.php` router file should be generated.

**Comment by TiagoSilvaPereira** [comment]
Hi @boskiv thank you for your suggestions. I'm closing here as it is already in the roadmap: https://trello.com/b/0MTU9Vyq/vemto-roadmap
