### ISSUE TITLE
[ENHANCEMENT] Add "exists:table,column" validation for the relationship fields

### ISSUE THREAD

**Issue by rohithmeethal** [TiagoSilvaPereira/vemto-issues#7]
**Is your feature request related to a problem? Please describe.**
By default no validation is added for relationship fields 

**Describe the solution you'd like**
On generating relationship, I want CRUD to include `exists:table,column` validation by default.

**Comment by TiagoSilvaPereira** [comment]
Thanks for your suggestion @rohithmeethal I'll add this option after finishing #10

**Comment by TiagoSilvaPereira** [comment]
Added to 0.5.2
