### ISSUE TITLE
[ENHANCEMENT] Export / Import Vemto Projects

### ISSUE THREAD

**Issue by graham-ch** [TiagoSilvaPereira/vemto-issues#70]
**Is your feature request related to a problem? Please describe.**

I switch between 2 PCs for work, the desktop during the day and the laptop in the evening.  I have no way of transferring Vemto projects between machines so I'm only ever able to work on a project on one machine.

**Describe the solution you'd like**

I can see two possible ways to accommodate my setup;

1) a way to export a Vemto project from one machine and a way to import a Vemto project into another machine.
2) a way to specify a shared/network folder for storing Vemto projects such that they're accessible using Vemto from any machine on the network.

**Describe alternatives you've considered**

I can't think of any way around this other than reverse engineering the Vemto app to see where the project files are stored to do some sort of manual file copy.

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch thank you for your suggestion... I'll close it for now as the option to Import/Export Projects is already on the roadmap (https://trello.com/b/0MTU9Vyq/vemto-roadmap)
