### ISSUE TITLE
[ENHANCEMENT] UI Template Creating / Editing / Copying

### ISSUE THREAD

**Issue by graham-ch** [TiagoSilvaPereira/vemto-issues#71]
**Is your feature request related to a problem? Please describe.**

After I have generated a web app from Vemto the first task I undertake is stripping out a lot of the generated UI to replace it with something a little more production ready. I often use elements from [Tailwind UI](https://tailwindui.com) and [Tailwind UI Kit](https://tailwinduikit.com) for this.

**Describe the solution you'd like**

I'd like a way of defining my own UI templates for generating Vemto projects.

**Describe alternatives you've considered**

Reverse engineering the Vemto app to see how UI templates are defined.

**Additional context**

The ability to load 3rd party UI Templates could open up an opportunity for Vemto to launch a UI Template / Plugin marketplace which would be beneficial to Vemto, customers and 3rd party Template/Plugin providers.

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch thank you for your suggestion... I'll close it for now as Custom Stubs and Plugins is already on the roadmap (https://trello.com/b/0MTU9Vyq/vemto-roadmap)

**Comment by graham-ch** [comment]
Thanks Tiago and sorry, I missed both suggestions on the roadmap.

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch no problems, please feel free to send me a suggestion, I'm analyzing each one :smile:
