### ISSUE TITLE
[BUG] Deleting pivot table leaves rogue relationships

### ISSUE THREAD

**Issue by graham-ch** [TiagoSilvaPereira/vemto-issues#72]
**Describe the bug**
I had a belongsToMany relationship between User and Team tables via a pivot table. Trying to delete the relationship was problematic (as in it wouldn't delete).

Upon deleting the pivot table, the relationships remained in the User and Team tables with no way to remove them via the UI. This also prevents any new relationships being created on the User / Team tables.

**To Reproduce**
1. Create Table A
2. Create Table B
3. Define a belongsToMany relationship between Table A and Table B
4. Delete the pivot table

**Expected behavior**
When a pivot table is deleted, the associated relationships should also be deleted.

**Screenshots**

![screen440](https://user-images.githubusercontent.com/4248589/106745138-992c5600-6618-11eb-8d5a-4099bf628c66.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 High Sierra
 - Vemto: 0.7.2

**Comment by graham-ch** [comment]
Ran the test again, created a belongsToMany between User table and Team table.

When deleting the relationship on the Team table, I get an Unhandled Error:

![screen442](https://user-images.githubusercontent.com/4248589/106746454-7ac75a00-661a-11eb-8872-edbeba47b668.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @graham-ch thank you for reporting this issue, I'll fix this for next Vemto version

**Comment by TiagoSilvaPereira** [comment]
@graham-ch fixed on 0.7.3
