### ISSUE TITLE
[BUG] Model name needs to be singular error incorrect

### ISSUE THREAD

**Issue by tkerns** [TiagoSilvaPereira/vemto-issues#77]
Version 0.7.7
**Describe the bug**
When I try to create a News model, I cannot, as it claims in needs to be singular

**To Reproduce**
1. Click Add Entity
2. Choose model
3. Set name to News
4. See error 'model name needs to be singular'

News IS singular :-)

**Comment by tkerns** [comment]
BTW, I found a workaround.  Create the model entity as 'New' instead of 'News'.  This will create the table and collection correctly.
Then after creation, edit entity, and change name from New to News.

**Comment by TiagoSilvaPereira** [comment]
Hi @tkerns thank you for reporting... I'll fix it for next version

**Comment by tkerns** [comment]
Just an FYI, my workaround didn't quite work.  In the news view it added:
`@forelse($news as $news)`
Which threw an error when trying to render the pagination links.
I had to change the controller variable to pass in $allNews, and then in the view change the forelse to
`@forelse($allNews as $news)`
That workaround seems to have worked for me, until the bug fix comes out.  Thanks!

**Comment by TiagoSilvaPereira** [comment]
Partially fixed on version 0.8.1 - needs to adapt the controller and routes to work correctly in such cases

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2
