### ISSUE TITLE
[BUG] Cannot see all CRUD applications on screen

### ISSUE THREAD

**Issue by tamilventhan** [TiagoSilvaPereira/vemto-issues#78]
**Describe the bug**
while add CRUD pages, can not see CRUD pages if its had more than 20 apps 
**To Reproduce**
1. Go to '...' Project Apps
2. Add more than 20 CRUD page
3. try to Scroll down 
4. find CRUD after 20th

**Expected behavior**
Page scrolling option will be help see all CRUD pages

**Comment by TiagoSilvaPereira** [comment]
Hi @tamilventhan thank you for reporting this issue... I'll fix it for the next Vemto version

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.7.8
