### ISSUE TITLE
[BUG] php serve use a port already in use

### ISSUE THREAD

**Issue by Gallyan** [TiagoSilvaPereira/vemto-issues#79]
**Describe the bug**
During the Run process, the launch of the server exit whit an error code because it use port 80 already in use by my local Apache webserver

**To Reproduce**
1. Launch Apache Locally
2. Click on "Run" in Vemto
3. Wait for the launch of the server
4. Error appears:Failed to listen on 127.0.0.1:80 (reason: Permission denied)

**Expected behavior**
A parameter to choose a port for the command "php -S 127.0.0.1:80 -t public/"

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by TiagoSilvaPereira** [comment]
Hi @Gallyan thank you for reporting... Vemto already has this option, you just need to add the port to the URL parameter on your Project Settings (by default, Vemto suggests using port 8000):

![image](https://user-images.githubusercontent.com/11933789/110114552-9a75ad80-7d93-11eb-8806-020901e972be.png)
