### ISSUE TITLE
[ENHANCEMENT] No warning about destructive behavior of generator

### ISSUE THREAD

**Issue by rohithmeethal** [TiagoSilvaPereira/vemto-issues#8]
**Describe the bug**
It isn't obvious on destructive behavior of generator, since it deletes all the files before regenerating.

**To Reproduce**
1. Generate code
2. Make modification to any file
3. Generate code

**Expected behavior**
Warning if any file is getting replaced.
Skip generating same files if the contents are same.
Track update of editing of resources so that only required files are modified.
May be make use version control commit, and pull request to merge the changes.

**Comment by TiagoSilvaPereira** [comment]
Hi @rohithmeethal thanks for your suggestion. As it isn't quite a bug, but a common behavior on code generators, I'll mark it as an enhancement. It is already in my plans and on the roadmap to track changes on individual files, but currently, I recommend using Vemto only to start new projects

**Comment by TiagoSilvaPereira** [comment]
I'll add a warning to the generation page too

**Comment by TiagoSilvaPereira** [comment]
Currently closing that as the current state of Vemto is to be a One-Side Code Generator... In the future, I think I can improve it to handle the current code and to work with existing projects. Thank you for your suggestion sir.
