### ISSUE TITLE
Add Jetstream Template In UI Template

### ISSUE THREAD

**Issue by simpaul13** [TiagoSilvaPereira/vemto-issues#81]
Hi 
I have just one request is the UI Template add A Jetstream Template

Laravel Jetstream Website
[Laravel Jetstream](https://jetstream.laravel.com/2.x/introduction.html)

**Comment by tamilventhan** [comment]
he is working on it will be realeased in next version of vemto

**Comment by TiagoSilvaPereira** [comment]
Hi @simpaul13 thank you for your suggestion, it is already being made for the next Vemto version. You can see all the features coming on our roadmap: https://trello.com/b/0MTU9Vyq/vemto-roadmap

Cheers
