### ISSUE TITLE
[SUGGESTION] Inertia option

### ISSUE THREAD

**Issue by computer-logix** [TiagoSilvaPereira/vemto-issues#85]
I program exclusively with Laravel using Inertia, so other than making the schema and dumping it into my own project I haven't used your product yet for any actual work.     Your Kanban shows an entry for inertia support as a 'maybe'   I certainly hope that changes someday to a feature request!   

If anyone else uses Laravel 8 Inertia mention it here so it gets on the development timeline.

**Comment by deanlj** [comment]
I would add that now jetstream is being used much more, the Intertia and LiveWire options would be in quite high demand.

I personally use LiveWire more than inertia but it would make sense for Vemto to generate interia or livewire depending on Jetstream version
