### ISSUE TITLE
Contact License

### ISSUE THREAD

**Issue by Parkbyounghyo** [TiagoSilvaPereira/vemto-issues#87]
Contact License
Can't I use multiple computers with a single license?
I have a Windows desktop and a MacBook.
There is no simultaneous connection.
Tell me how I can share the license.

**Comment by TiagoSilvaPereira** [comment]
Hi @Parkbyounghyo, no, the license is for one computer, as you can see on the Vemto website (https//vemto.app). Please send me an email if you have more questions: contact@vemto.app
