### ISSUE TITLE
[BUG]  Error in the seeder when entity has multiple  relationships to their own records

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#88]
I am using an entity that has multiple relationships with different parent records of the same entity and, accordingly, any number of child relationships from any record. (see figure)
But this model causes an error in the seeder and all seeders after the error are not executed.

![nnn_5-0](https://user-images.githubusercontent.com/80303996/111035945-53508200-844f-11eb-9c89-ddb7440462bd.jpg)
![nnn_5-1](https://user-images.githubusercontent.com/80303996/111035957-5e0b1700-844f-11eb-95b4-d78bf8ae6a10.jpg)
![nnn_5-5](https://user-images.githubusercontent.com/80303996/111035962-64998e80-844f-11eb-9023-b9f50f748ce7.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 thank you for reporting, I'll fix this bug as soon as possible, once I discover what is happening with the Seeder. Cheers

**Comment by TiagoSilvaPereira** [comment]
Fixed on version 0.8.1
