### ISSUE TITLE
[BUG] An error was detected in the interaction between Shema Editor and CRUD Editor

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#89]
If you have already configured the application in CRUD Editor, and then accidentally click on the model fields in Sсhema Editor, then all the settings of the corresponding component in CRUD Editor are reset to default values, and the component itself moves to the top of the list of components in the form, knocking down the manually configured layout of the form.
I have 80 models in the project and working with forms sometimes it is necessary to change something in the Sсhema Editor and if I accidentally touch the wrong model, I lose the settings of the appropriate form. With such a large project, there is a very high risk of getting an uncontrolled loss of some of the settings of previously completed forms. Therefore, it is extremely important that cosmetic changes to the Sсhema editor do not affect the CRUD Editor, such as:
1. Click on the model field
2. Changing the order of the list of model fields
3. Changing the name of the model field
In no case should such changes to the model fields in the Shema Editor change the existing setting of the corresponding form component in the CRUD editor associated with this field ! ! !

![nnn_6-1](https://user-images.githubusercontent.com/80303996/111059148-c268bd80-84c5-11eb-98cc-4a4a1ecca7f7.jpg)
![nnn_6-2](https://user-images.githubusercontent.com/80303996/111059152-c85e9e80-84c5-11eb-8169-6e2dc37ec4c4.jpg)
![nnn_6-3](https://user-images.githubusercontent.com/80303996/111059153-cdbbe900-84c5-11eb-8855-842c0e07aedb.jpg)

**Comment by TiagoSilvaPereira** [comment]
@StasKoun2 thank you for reporting

**Comment by TiagoSilvaPereira** [comment]
Fixed on version 0.8.1
