### ISSUE TITLE
[BUG] check for npm always fails in Ubuntu even if it exists

### ISSUE THREAD

**Issue by rohithmeethal** [TiagoSilvaPereira/vemto-issues#9]
**Describe the bug**
Even if npm exists in the path or we give absolute folder path, it still fails.
I think it is because the way npm is checked.
executing just `npm` will give exit status as 1 in my terminal. So if the script is checking for exit status 0 this fails.
If you run something like `npm version` instead, exit status would be 0.

**To Reproduce**
Try to run "RUN" from vemto in Ubuntu with absolute path given or npm included in the path.

You can understand the behavior of exit code by running `npm` in terminal and then using `echo $?`

**Expected behavior**
npm should be detected as found

**Comment by TiagoSilvaPereira** [comment]
@rohithmeethal Thanks for reporting it 

Fixed on 0.4.15
