### ISSUE TITLE
[BUG] Error after NPM RUN DEV - 'mix' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by kominfosekadau** [TiagoSilvaPereira/vemto-issues#91]
**Describe the bug**

Generate success,
Composser Instal success,
NPM Install success.

NPM run dev I got this error:

'mix' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-03-19T02_09_34_919Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-03-19T02_09_35_014Z-debug.log

**Desktop (please complete the following information):**
 - OS: windows 10
- Laragon
- NOde JS 14.16
- PHP 7.4

**Comment by TiagoSilvaPereira** [comment]
Hi @kominfosekadau thank you for reporting... could you please share your package.json file?

**Comment by TiagoSilvaPereira** [comment]
Hi @kominfosekadau I'm closing for now as this issue seems not to be related to Vemto. But feel free to ask here if I can help you to solve this (you can try running the **npm install** and **npm run dev** commands directly on your command line)
