### ISSUE TITLE
[ENHANCEMENT] Not delete route

### ISSUE THREAD

**Issue by edisonfv** [TiagoSilvaPereira/vemto-issues#93]
**Is your feature request related to a problem? Please describe.**
When I update the project and generate the code, The files of routes restart the value and delete the avance of work.

**Describe alternatives you've considered**
When generate the code, the software should backup the content  the files of routes

**Comment by TiagoSilvaPereira** [comment]
Hi @edisonfv I'm changing this behavior for the next version (it will never remove changed files)

**Comment by TiagoSilvaPereira** [comment]
Feature added to version 0.8.1
