### ISSUE TITLE
[SUGGESTION] Don't Overwrite webpack.mix.js

### ISSUE THREAD

**Issue by koraycicekciogullari** [TiagoSilvaPereira/vemto-issues#94]
**Is your feature request related to a problem? Please describe.**
I make specific settings and configurations in my project. When I create code with Vemto, it overwrites the webpack.mix.js file and all my configurations disappear.

**Describe alternatives you've considered**
If the webpack.mix.js file exists, do not overwrite it.

Thanks.

**Comment by TiagoSilvaPereira** [comment]
Hi @koraycicekciogullari it is coming in the next version

**Comment by TiagoSilvaPereira** [comment]
Feature added to version 0.8.1
