### ISSUE TITLE
[SUGGESTION] Import and export projects

### ISSUE THREAD

**Issue by ddiaz2380** [TiagoSilvaPereira/vemto-issues#95]
Is it possible to add the function of importing and exporting projects? I have some in laravel 7 and 8 made before acquiring vemto and the truth is I would like to be able to import them to continue working with the tool.

**Comment by TiagoSilvaPereira** [comment]
Hi @ddiaz2380 thank you for your suggeston... I'm closing as it is already on the Roadmap: https://trello.com/b/0MTU9Vyq/vemto-roadmap
