### ISSUE TITLE
[BUG] Feature Tests don't account for Soft Deletes

### ISSUE THREAD

**Issue by jchandler** [TiagoSilvaPereira/vemto-issues#98]
**Describe the bug**
In the generated feature tests, the function `$this->assertDeleted(}` is always run.  But for entities with soft deletes, the function should be `$this->assertSoftDeleted()`.

**To Reproduce**
1. Use Vemto 0.7.8
2. Create an entity with soft deletes enabled
2. Make sure to generate the tests for that entity
3. Run the test suite
4. See that the delete test fails every time

**Expected behavior**
Tests should pass when newly generated, with no changes.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Command line

**Comment by TiagoSilvaPereira** [comment]
Hi @jchandler thank you for reporting, I'll fix this bug for next version

**Comment by TiagoSilvaPereira** [comment]
Fixed on version 0.8.1
